package service

import (
	"context"
	"errors"
	"fmt"
	"io/fs"
	"os"
	"strings"

	"github.com/cafecito-games/grafo/internal/agentinstall"
)

// DefinitionVersion is the version marker embedded in every generated service
// definition. It is compared exactly, so a definition generated by a future
// Grafo is reported instead of being silently replaced.
const DefinitionVersion = "1"

// Label is the launchd label and the systemd unit stem of Grafo's supervisor.
const Label = "games.cafecito.grafo.index"

// SystemdUnit is the user unit file name.
const SystemdUnit = "grafo-index.service"

// Change values reported by service operations.
const (
	ChangeInstalled = "installed"
	ChangeUpdated   = "updated"
	ChangeRemoved   = "removed"
	ChangeUnchanged = "unchanged"
	ChangeSkipped   = "skipped"
)

// Action is one service-management step that was taken, or in a dry run one that
// would be taken.
type Action struct {
	Platform string `json:"platform"`
	Kind     string `json:"kind"` // "definition", "activate", "deactivate", "restart"
	Target   string `json:"target"`
	Change   string `json:"change"`
	DryRun   bool   `json:"dry_run,omitempty"`
	Detail   string `json:"detail,omitempty"`
}

// State is what the platform reports about Grafo's installed service.
type State struct {
	Platform  string `json:"platform"`
	Supported bool   `json:"supported"`
	// Definition is the generated unit or plist path.
	Definition string `json:"definition,omitempty"`
	Installed  bool   `json:"definition_installed"`
	// Owned reports that a receipt proves Grafo wrote exactly the bytes on disk.
	Owned bool `json:"definition_owned"`
	// Conflict reports a definition at Grafo's path that Grafo cannot prove it
	// wrote. It is reported and never replaced without an explicit repair.
	Conflict bool   `json:"definition_conflict,omitempty"`
	Loaded   bool   `json:"loaded"`
	Running  bool   `json:"running"`
	Detail   string `json:"detail,omitempty"`
}

// Platform is the operating-system integration for the background supervisor.
// It owns the generated definition content; doctor and the CLI consume it.
type Platform interface {
	// Name reports the init system ("launchd", "systemd", or "unsupported").
	Name() string
	// Supported reports whether service installation works on this host.
	Supported() bool
	// DefinitionPath resolves the user-scoped definition file.
	DefinitionPath(reader agentinstall.Reader) (string, error)
	// Definition renders the exact content Grafo generates for this host.
	Definition(binary, stateDir string) string
	// activate loads and starts the service; deactivate stops and unloads it.
	activate(ctx context.Context, env agentinstall.Environment) error
	deactivate(ctx context.Context, env agentinstall.Environment) error
	// Restart restarts a running or stale service.
	Restart(ctx context.Context, env agentinstall.Environment) error
	// runtime reports whether the init system has the service loaded and running.
	runtime(ctx context.Context, reader agentinstall.Reader) (loaded, running bool, detail string)
}

// PlatformFor returns the service adapter for the target operating system.
func PlatformFor(goos string) Platform {
	switch goos {
	case "darwin":
		return launchd{}
	case "linux":
		return systemd{}
	default:
		return unsupportedPlatform{goos: goos}
	}
}

// Describe reports the platform state without mutating anything.
func Describe(ctx context.Context, env agentinstall.Environment) (State, error) {
	platform := PlatformFor(env.GOOS())
	state := State{Platform: platform.Name(), Supported: platform.Supported()}
	if !platform.Supported() {
		state.Detail = fmt.Sprintf("background service installation is not supported on %s yet; use 'grafo watch' in a foreground terminal", env.GOOS())
		return state, nil
	}
	path, err := platform.DefinitionPath(env)
	if err != nil {
		return state, err
	}
	state.Definition = path
	contents, readErr := env.ReadFile(path)
	if readErr == nil {
		state.Installed = true
		receipt, found, receiptErr := agentinstall.OwnedFile(env, agentinstall.ServiceOwner, platform.Name())
		if receiptErr != nil {
			return state, receiptErr
		}
		state.Owned = found && agentinstall.ProvesFile(receipt, path, string(contents))
		state.Conflict = !state.Owned
		if state.Conflict {
			state.Detail = "a service definition at Grafo's path does not match anything Grafo recorded writing"
		}
	} else if !errors.Is(readErr, fs.ErrNotExist) {
		state.Detail = readErr.Error()
	}
	state.Loaded, state.Running, _ = platform.runtime(ctx, env)
	return state, nil
}

// Install writes the generated definition and activates the service. It is
// idempotent: an already-correct definition is reported unchanged and the
// activation commands are replayed, which every supported init system accepts.
func Install(ctx context.Context, env agentinstall.Environment, binary, stateDir string, dryRun bool) ([]Action, error) {
	platform := PlatformFor(env.GOOS())
	if !platform.Supported() {
		return nil, fmt.Errorf("background service installation is not supported on %s yet; run 'grafo watch' in a foreground terminal instead", env.GOOS())
	}
	path, err := platform.DefinitionPath(env)
	if err != nil {
		return nil, err
	}
	if err := agentinstall.CheckUserConfigRoot(env, path); err != nil {
		return nil, fmt.Errorf("refusing to write service definition %s: %w", path, err)
	}
	generated := platform.Definition(binary, stateDir)
	current, readErr := env.ReadFile(path)
	action := Action{Platform: platform.Name(), Kind: "definition", Target: path, DryRun: dryRun}
	switch {
	case readErr != nil && errors.Is(readErr, fs.ErrNotExist):
		action.Change = ChangeInstalled
	case readErr != nil:
		return nil, fmt.Errorf("read service definition %s: %w", path, readErr)
	case string(current) == generated:
		action.Change = ChangeUnchanged
	default:
		receipt, found, receiptErr := agentinstall.OwnedFile(env, agentinstall.ServiceOwner, platform.Name())
		if receiptErr != nil {
			return nil, receiptErr
		}
		if !found || !agentinstall.ProvesFile(receipt, path, string(current)) {
			action.Change = ChangeSkipped
			action.Detail = "existing definition differs from Grafo's generated content and Grafo cannot prove it wrote it; move it aside and re-run"
			return []Action{action}, fmt.Errorf("service definition %s conflicts with Grafo's generated content; move it aside and re-run", path)
		}
		action.Change = ChangeUpdated
	}
	if dryRun {
		return []Action{action, {Platform: platform.Name(), Kind: "activate", Target: Label, Change: ChangeUnchanged, DryRun: true}}, nil
	}
	if action.Change != ChangeUnchanged {
		if directory := agentinstall.ParentPath(env.GOOS(), path); directory != "" {
			if err := env.MkdirAll(directory, 0o755); err != nil {
				return nil, fmt.Errorf("create service directory %s: %w", directory, err)
			}
		}
		if err := env.WriteFileAtomic(path, []byte(generated), 0o644); err != nil {
			return nil, fmt.Errorf("write service definition %s: %w", path, err)
		}
		if err := agentinstall.RecordOwnedFile(env, agentinstall.ServiceOwner, platform.Name(), path, generated); err != nil {
			return nil, err
		}
	} else if err := agentinstall.RecordOwnedFile(env, agentinstall.ServiceOwner, platform.Name(), path, generated); err != nil {
		// Recording an already-correct definition keeps the ledger accurate after a
		// reinstall over content Grafo generated but never recorded.
		return nil, err
	}
	actions := []Action{action}
	activation := Action{Platform: platform.Name(), Kind: "activate", Target: Label, Change: ChangeInstalled}
	if err := platform.activate(ctx, env); err != nil {
		activation.Change = ChangeSkipped
		activation.Detail = err.Error()
		return append(actions, activation), err
	}
	return append(actions, activation), nil
}

// Uninstall deactivates the service and removes the definition, but only when a
// receipt proves Grafo wrote exactly the bytes on disk. Anything else is left in
// place and reported. Uninstalling twice is not an error.
func Uninstall(ctx context.Context, env agentinstall.Environment, dryRun bool) ([]Action, error) {
	platform := PlatformFor(env.GOOS())
	if !platform.Supported() {
		return nil, fmt.Errorf("background service installation is not supported on %s yet", env.GOOS())
	}
	path, err := platform.DefinitionPath(env)
	if err != nil {
		return nil, err
	}
	actions := []Action{{Platform: platform.Name(), Kind: "deactivate", Target: Label, Change: ChangeRemoved, DryRun: dryRun}}
	if !dryRun {
		if err := platform.deactivate(ctx, env); err != nil {
			actions[0].Change = ChangeSkipped
			actions[0].Detail = err.Error()
		}
	}
	action := Action{Platform: platform.Name(), Kind: "definition", Target: path, DryRun: dryRun}
	current, readErr := env.ReadFile(path)
	switch {
	case readErr != nil && errors.Is(readErr, fs.ErrNotExist):
		action.Change = ChangeUnchanged
		action.Detail = "no service definition is installed"
		if !dryRun {
			if err := agentinstall.ForgetOwnedFile(env, agentinstall.ServiceOwner, platform.Name()); err != nil {
				return append(actions, action), err
			}
		}
		return append(actions, action), nil
	case readErr != nil:
		return actions, fmt.Errorf("read service definition %s: %w", path, readErr)
	}
	receipt, found, receiptErr := agentinstall.OwnedFile(env, agentinstall.ServiceOwner, platform.Name())
	if receiptErr != nil {
		return actions, receiptErr
	}
	if !found || !agentinstall.ProvesFile(receipt, path, string(current)) {
		action.Change = ChangeSkipped
		action.Detail = "Grafo cannot prove it wrote this definition; remove it manually if you no longer want it"
		return append(actions, action), nil
	}
	action.Change = ChangeRemoved
	if dryRun {
		return append(actions, action), nil
	}
	if err := env.Remove(path); err != nil && !errors.Is(err, fs.ErrNotExist) {
		return append(actions, action), fmt.Errorf("remove service definition %s: %w", path, err)
	}
	if err := agentinstall.ForgetOwnedFile(env, agentinstall.ServiceOwner, platform.Name()); err != nil {
		return append(actions, action), err
	}
	return append(actions, action), nil
}

// ---------------------------------------------------------------------------
// launchd (macOS user agent)
// ---------------------------------------------------------------------------

type launchd struct{}

func (launchd) Name() string { return "launchd" }

func (launchd) Supported() bool { return true }

func (launchd) DefinitionPath(reader agentinstall.Reader) (string, error) {
	return agentinstall.HomeDirPath(reader, "Library", "LaunchAgents", Label+".plist")
}

func (launchd) Definition(binary, stateDir string) string {
	logs := LogPath(stateDir)
	return `<?xml version="1.0" encoding="UTF-8"?>
<!-- grafo-service-definition: ` + DefinitionVersion + ` -->
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
  <key>Label</key>
  <string>` + Label + `</string>
  <key>ProgramArguments</key>
  <array>
    <string>` + escapeXML(binary) + `</string>
    <string>service</string>
    <string>run</string>
    <string>--state-dir</string>
    <string>` + escapeXML(stateDir) + `</string>
  </array>
  <key>RunAtLoad</key>
  <true/>
  <key>KeepAlive</key>
  <true/>
  <key>ProcessType</key>
  <string>Background</string>
  <key>StandardOutPath</key>
  <string>` + escapeXML(logs+".out") + `</string>
  <key>StandardErrorPath</key>
  <string>` + escapeXML(logs+".err") + `</string>
</dict>
</plist>
`
}

// domain is the launchd GUI domain of the current user.
func (launchd) domain() string { return fmt.Sprintf("gui/%d", os.Getuid()) }

func (l launchd) activate(ctx context.Context, env agentinstall.Environment) error {
	path, err := l.DefinitionPath(env)
	if err != nil {
		return err
	}
	// Bootout first so bootstrap is replayable; an unloaded service makes bootout
	// fail, which is not an error here.
	_, _ = env.Run(ctx, "launchctl", "bootout", l.domain()+"/"+Label)
	if output, err := env.Run(ctx, "launchctl", "bootstrap", l.domain(), path); err != nil {
		return fmt.Errorf("launchctl bootstrap: %w: %s", err, strings.TrimSpace(string(output)))
	}
	return nil
}

func (l launchd) deactivate(ctx context.Context, env agentinstall.Environment) error {
	if _, err := env.Run(ctx, "launchctl", "bootout", l.domain()+"/"+Label); err != nil {
		// A service that is not loaded is already deactivated.
		return nil
	}
	return nil
}

func (l launchd) Restart(ctx context.Context, env agentinstall.Environment) error {
	if output, err := env.Run(ctx, "launchctl", "kickstart", "-k", l.domain()+"/"+Label); err != nil {
		return fmt.Errorf("launchctl kickstart: %w: %s", err, strings.TrimSpace(string(output)))
	}
	return nil
}

func (l launchd) runtime(ctx context.Context, reader agentinstall.Reader) (bool, bool, string) {
	output, err := reader.Output(ctx, "launchctl", "print", l.domain()+"/"+Label)
	if err != nil {
		return false, false, "service is not loaded"
	}
	text := string(output)
	return true, strings.Contains(text, "state = running") || strings.Contains(text, "pid = "), ""
}

// ---------------------------------------------------------------------------
// systemd (Linux user unit)
// ---------------------------------------------------------------------------

type systemd struct{}

func (systemd) Name() string { return "systemd" }

func (systemd) Supported() bool { return true }

func (systemd) DefinitionPath(reader agentinstall.Reader) (string, error) {
	return agentinstall.ConfigHomePath(reader, "systemd", "user", SystemdUnit)
}

func (systemd) Definition(binary, stateDir string) string {
	return `# grafo-service-definition: ` + DefinitionVersion + `
# Generated by grafo; edits are replaced on the next 'grafo service install'.
[Unit]
Description=Grafo background repository indexing
Documentation=https://github.com/cafecito-games/grafo

[Service]
Type=simple
ExecStart=` + binary + ` service run --state-dir ` + stateDir + `
Restart=on-failure
RestartSec=5
Nice=10

[Install]
WantedBy=default.target
`
}

func (systemd) activate(ctx context.Context, env agentinstall.Environment) error {
	if output, err := env.Run(ctx, "systemctl", "--user", "daemon-reload"); err != nil {
		return fmt.Errorf("systemctl --user daemon-reload: %w: %s", err, strings.TrimSpace(string(output)))
	}
	if output, err := env.Run(ctx, "systemctl", "--user", "enable", "--now", SystemdUnit); err != nil {
		return fmt.Errorf("systemctl --user enable --now %s: %w: %s", SystemdUnit, err, strings.TrimSpace(string(output)))
	}
	return nil
}

func (systemd) deactivate(ctx context.Context, env agentinstall.Environment) error {
	_, _ = env.Run(ctx, "systemctl", "--user", "disable", "--now", SystemdUnit)
	_, _ = env.Run(ctx, "systemctl", "--user", "daemon-reload")
	return nil
}

func (systemd) Restart(ctx context.Context, env agentinstall.Environment) error {
	if output, err := env.Run(ctx, "systemctl", "--user", "restart", SystemdUnit); err != nil {
		return fmt.Errorf("systemctl --user restart %s: %w: %s", SystemdUnit, err, strings.TrimSpace(string(output)))
	}
	return nil
}

func (systemd) runtime(ctx context.Context, reader agentinstall.Reader) (bool, bool, string) {
	loaded := false
	if output, err := reader.Output(ctx, "systemctl", "--user", "is-enabled", SystemdUnit); err == nil {
		loaded = strings.TrimSpace(string(output)) != ""
	}
	running := false
	if output, err := reader.Output(ctx, "systemctl", "--user", "is-active", SystemdUnit); err == nil {
		running = strings.TrimSpace(string(output)) == "active"
	}
	return loaded, running, ""
}

// ---------------------------------------------------------------------------
// Unsupported platforms
// ---------------------------------------------------------------------------

type unsupportedPlatform struct{ goos string }

func (unsupportedPlatform) Name() string { return "unsupported" }

func (unsupportedPlatform) Supported() bool { return false }

func (u unsupportedPlatform) DefinitionPath(agentinstall.Reader) (string, error) {
	return "", fmt.Errorf("no service definition location is defined for %s", u.goos)
}

func (unsupportedPlatform) Definition(string, string) string { return "" }

func (u unsupportedPlatform) activate(context.Context, agentinstall.Environment) error {
	return fmt.Errorf("background service installation is not supported on %s yet", u.goos)
}

func (u unsupportedPlatform) deactivate(context.Context, agentinstall.Environment) error {
	return nil
}

func (u unsupportedPlatform) Restart(context.Context, agentinstall.Environment) error {
	return fmt.Errorf("background service installation is not supported on %s yet", u.goos)
}

func (unsupportedPlatform) runtime(context.Context, agentinstall.Reader) (bool, bool, string) {
	return false, false, ""
}

// escapeXML escapes the characters that are not legal inside a plist string.
func escapeXML(value string) string {
	replacer := strings.NewReplacer("&", "&amp;", "<", "&lt;", ">", "&gt;", `"`, "&quot;", "'", "&apos;")
	return replacer.Replace(value)
}
