package protobufbinding_test

import (
	"context"
	"os"
	"path/filepath"
	"strings"
	"testing"

	"github.com/cafecito-games/grafo/internal/graph"
	parserapi "github.com/cafecito-games/grafo/internal/parser"
	"github.com/cafecito-games/grafo/internal/parser/protobufbinding"
)

func TestParserProjectsSupportedGoAndGDScriptBindings(t *testing.T) {
	root := fixture(t, `version: v2
managed:
  enabled: true
  override:
    - file_option: go_package_prefix
      value: example.com/generated
plugins:
  - remote: buf.build/protocolbuffers/go:v1.36.11
    out: gen/go
    opt: paths=source_relative
  - local: protoc-gen-gdscript
    out: gen/gd
`)
	loader := protobufbinding.NewLoader()
	content, err := os.ReadFile(filepath.Join(root, "buf.gen.yaml"))
	if err != nil {
		t.Fatal(err)
	}
	result, err := protobufbinding.New(loader).Parse(context.Background(), parserapi.Input{
		Root: root, Path: "buf.gen.yaml", Content: content, Repository: "fixture", RepoID: "repo:fixture",
	})
	if err != nil {
		t.Fatal(err)
	}
	if len(result.Diagnostics) != 0 {
		t.Fatalf("unexpected diagnostics: %#v", result.Diagnostics)
	}

	assertProjection(t, result, graph.KindType, "example.com/generated/acme/v1.Envelope", "acme.v1.Envelope")
	assertProjection(t, result, graph.KindMethod, "example.com/generated/acme/v1.Envelope.GetText", "acme.v1.Envelope.text")
	assertProjection(t, result, graph.KindType, "example.com/generated/acme/v1.Envelope_Text", "acme.v1.Envelope.text")
	assertProjection(t, result, graph.KindMethod, "example.com/generated/acme/v1.Envelope.GetText_2", "acme.v1.Envelope.text_2")
	assertProjection(t, result, graph.KindType, "example.com/generated/acme/v1.Envelope_Text_2", "acme.v1.Envelope.text_2")
	assertProjection(t, result, graph.KindMethod, "example.com/generated/acme/v1.Envelope.GetText2", "acme.v1.Envelope.text2")
	assertProjection(t, result, graph.KindMethod, "example.com/generated/acme/v1.Envelope.GetXPrivate", "acme.v1.Envelope._private")
	assertProjection(t, result, graph.KindClass, "AcmeV1EnvelopeEnvelope", "acme.v1.Envelope")
	assertProjection(t, result, graph.KindMethod, "AcmeV1EnvelopeEnvelope.set_text", "acme.v1.Envelope.text")
	assertProjection(t, result, graph.KindMethod, "AcmeV1EnvelopeEnvelope.has_text", "acme.v1.Envelope.text")
	assertProjection(t, result, graph.KindMethod, "AcmeV1EnvelopeEnvelope.add_tags", "acme.v1.Envelope.tags")
	assertProjection(t, result, graph.KindMethod, "AcmeV1EnvelopeEnvelope.new_child", "acme.v1.Envelope.child")
	assertProjection(t, result, graph.KindMethod, "AcmeV1EnvelopeEnvelope.set_state", "acme.v1.Envelope.state")
	assertProjection(t, result, graph.KindClass, "AcmeV1EnvelopeState", "acme.v1.State")
	assertProjection(t, result, graph.KindType, "AcmeV1EnvelopeState.State", "acme.v1.State")
	assertProjection(t, result, graph.KindField, "example.com/generated/acme/v1.State_STATE_READY", "acme.v1.State.STATE_READY")
	assertProjection(t, result, graph.KindField, "AcmeV1EnvelopeState.State.STATE_READY", "acme.v1.State.STATE_READY")

	registry, err := loader.Load(context.Background(), parserapi.Input{Root: root, Repository: "fixture", RepoID: "repo:fixture"})
	if err != nil {
		t.Fatal(err)
	}
	goHeader := []byte("// Code generated by protoc-gen-go. DO NOT EDIT.\n// source: acme/v1/envelope.proto\npackage acmev1\n")
	if _, ok, reason := registry.GeneratedFile("gen/go/acme/v1/envelope.pb.go", "go", goHeader); !ok || reason != "" {
		t.Fatalf("Go output not recognized: ok=%v reason=%q", ok, reason)
	}
	gdHeader := []byte("class_name AcmeV1EnvelopeEnvelope\n# Generated by gdproto\n# Source: envelope.proto\n# DO NOT EDIT\n")
	if _, ok, reason := registry.GeneratedFile("gen/gd/AcmeV1EnvelopeEnvelope.pb.gd", "gdscript", gdHeader); !ok || reason != "" {
		t.Fatalf("GDScript output not recognized: ok=%v reason=%q", ok, reason)
	}
	if _, ok, _ := registry.GeneratedFile("gen/go/acme/v1/envelope.pb.go", "go", []byte("// Code generated by another tool. DO NOT EDIT.")); ok {
		t.Fatal("non-Protobuf generated Go was suppressed")
	}
}

func TestRegistryRejectsAmbiguousGDScriptHeaderBasename(t *testing.T) {
	root := fixture(t, "version: v2\nplugins:\n  - local: protoc-gen-gdscript\n    out: gen\n")
	write(t, root, "proto/other/v1/envelope.proto", "syntax = \"proto3\"; package other.v1; message Envelope {}\n")
	loader := protobufbinding.NewLoader()
	registry, err := loader.Load(context.Background(), parserapi.Input{Root: root, RepoID: "repo:test"})
	if err != nil {
		t.Fatal(err)
	}
	header := []byte("# Generated by gdproto\n# Source: envelope.proto\n# DO NOT EDIT\n")
	if _, ok, reason := registry.GeneratedFile("gen/AcmeV1EnvelopeEnvelope.pb.gd", "gdscript", header); ok || !strings.Contains(reason, "more than one configured schema") {
		t.Fatalf("ambiguous basename accepted: ok=%v reason=%q", ok, reason)
	}
}

func TestManagedOverrideRequiresManagedMode(t *testing.T) {
	root := fixture(t, `version: v2
managed:
  enabled: false
  override:
    - file_option: go_package_prefix
      value: example.com/incorrect
plugins:
  - remote: buf.build/protocolbuffers/go:v1.36.11
    out: gen
    opt: paths=source_relative
`)
	write(t, root, "proto/acme/v1/envelope.proto", `syntax = "proto3";
package acme.v1;
option go_package = "example.com/from-option;acmev1";
message Envelope {}
`)
	content, _ := os.ReadFile(filepath.Join(root, "buf.gen.yaml"))
	result, err := protobufbinding.New(nil).Parse(context.Background(), parserapi.Input{Root: root, Path: "buf.gen.yaml", Content: content, RepoID: "repo:test"})
	if err != nil {
		t.Fatal(err)
	}
	assertProjection(t, result, graph.KindType, "example.com/from-option.Envelope", "acme.v1.Envelope")
}

func TestLoaderDiagnosesAndSkipsUnreadableSemanticInput(t *testing.T) {
	root := fixture(t, "version: v2\nplugins:\n  - local: protoc-gen-gdscript\n    out: gen\n")
	schema := filepath.Join(root, "proto", "acme", "v1", "envelope.proto")
	if err := os.Remove(schema); err != nil {
		t.Fatal(err)
	}
	if err := os.Symlink("missing.proto", schema); err != nil {
		t.Fatal(err)
	}
	content, _ := os.ReadFile(filepath.Join(root, "buf.gen.yaml"))
	result, err := protobufbinding.New(nil).Parse(context.Background(), parserapi.Input{Root: root, Path: "buf.gen.yaml", Content: content, RepoID: "repo:test"})
	if err != nil {
		t.Fatalf("unreadable schema aborted binding registry: %v", err)
	}
	if len(result.Diagnostics) == 0 || !strings.Contains(result.Diagnostics[0].Message, "read Protobuf binding input") {
		t.Fatalf("unreadable schema was not diagnosed: %#v", result.Diagnostics)
	}
	for _, node := range result.Nodes {
		if node.Properties["generated_binding"] == "true" {
			t.Fatalf("unreadable schema produced a projection: %#v", node)
		}
	}
}

func TestParserRejectsMalformedAndUnsupportedGenerationConfiguration(t *testing.T) {
	tests := []struct{ name, config, want string }{
		{"malformed", "version: [", "parse Buf generation configuration"},
		{"unknown-plugin", "version: v2\nplugins:\n  - local: mystery-generator\n    out: gen\n", "unsupported Protobuf generator"},
		{"unsupported-go-mode", "version: v2\nplugins:\n  - remote: buf.build/protocolbuffers/go:v1.36.11\n    out: gen\n", "paths=source_relative"},
		{"unsupported-go-option", "version: v2\nplugins:\n  - remote: buf.build/protocolbuffers/go:v1.36.11\n    out: gen\n    opt: [paths=source_relative,Mfoo.proto=example.com/foo]\n", "option is not supported"},
	}
	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			root := fixture(t, tt.config)
			content, _ := os.ReadFile(filepath.Join(root, "buf.gen.yaml"))
			result, err := protobufbinding.New(nil).Parse(context.Background(), parserapi.Input{Root: root, Path: "buf.gen.yaml", Content: content, RepoID: "repo:test"})
			if err != nil {
				t.Fatal(err)
			}
			if len(result.Diagnostics) == 0 || !strings.Contains(result.Diagnostics[0].Message, tt.want) {
				t.Fatalf("diagnostics=%#v, want %q", result.Diagnostics, tt.want)
			}
			for _, node := range result.Nodes {
				if node.Properties["generated_binding"] == "true" {
					t.Fatalf("invalid configuration emitted projection: %#v", node)
				}
			}
		})
	}
}

func fixture(t *testing.T, config string) string {
	t.Helper()
	root := t.TempDir()
	write(t, root, "buf.yaml", "version: v2\nmodules:\n  - path: proto\nlint:\n  use: [STANDARD]\n")
	write(t, root, "buf.gen.yaml", config)
	write(t, root, "proto/acme/v1/envelope.proto", `syntax = "proto3";
package acme.v1;
message Envelope {
	oneof payload {
		string text = 1;
		string text_2 = 5;
	}
  repeated string tags = 2;
  Child child = 3;
  State state = 4;
	string text2 = 6;
	string _private = 7;
}
message Child {}
enum State { STATE_UNSPECIFIED = 0; STATE_READY = 1; }
`)
	return root
}
func write(t *testing.T, root, path, content string) {
	t.Helper()
	full := filepath.Join(root, filepath.FromSlash(path))
	if err := os.MkdirAll(filepath.Dir(full), 0o755); err != nil {
		t.Fatal(err)
	}
	if err := os.WriteFile(full, []byte(content), 0o644); err != nil {
		t.Fatal(err)
	}
}
func assertProjection(t *testing.T, result graph.ParseResult, kind graph.NodeKind, qualified, canonical string) {
	t.Helper()
	for _, node := range result.Nodes {
		if node.Kind != kind || node.QualifiedName != qualified {
			continue
		}
		for _, fact := range result.Facts {
			if fact.FromID == node.ID && fact.Kind == graph.EdgeGeneratedFrom && fact.Target == canonical {
				if fact.TargetID == "" {
					t.Fatalf("projection %q did not retain canonical schema identity", qualified)
				}
				return
			}
		}
		t.Fatalf("projection %q has no generated_from edge", qualified)
	}
	t.Fatalf("missing %s projection %q", kind, qualified)
}
