package gdscript_test

import (
	"context"
	"os"
	"path/filepath"
	"strings"
	"testing"

	"github.com/cafecito-games/grafo/internal/graph"
	parserapi "github.com/cafecito-games/grafo/internal/parser"
	gdscriptparser "github.com/cafecito-games/grafo/internal/parser/gdscript"
)

func TestParserExtractsGodotSymbolsAndWiring(t *testing.T) {
	content := []byte(`class_name Player extends CharacterBody2D

signal health_changed(value: int)
const Enemy = preload('res://actors/enemy.gd')
const EnemyUID = preload('uid://enemy123')
@export var speed: float = 10.0
var health: int = 100

func take_damage(amount: int) -> int:
	var applied: int = amount
	var enemy: Enemy = Enemy.new()
	health = applied
	health_changed.emit(health)
	health_changed.connect(on_health_changed)
	enemy.attack(applied)
	var mode = OS.get_environment("GAME_MODE")
	return applied
`)
	result, err := gdscriptparser.New().Parse(context.Background(), parserapi.Input{
		Path: "actors/player.gd", Content: content, Repository: "sample", RepoID: "repo:sample",
	})
	if err != nil {
		t.Fatal(err)
	}
	assertHasNode(t, result.Nodes, graph.KindClass, "Player")
	assertHasNode(t, result.Nodes, graph.KindMethod, "take_damage")
	assertHasNode(t, result.Nodes, graph.KindParameter, "amount")
	assertHasNode(t, result.Nodes, graph.KindField, "speed")
	assertHasNode(t, result.Nodes, graph.KindField, "health")
	assertHasNode(t, result.Nodes, graph.KindVariable, "applied")
	assertHasNode(t, result.Nodes, graph.KindEvent, "health_changed")
	assertHasFact(t, result.Facts, graph.EdgeExtends, "CharacterBody2D")
	assertHasFact(t, result.Facts, graph.EdgeImports, "actors/enemy")
	assertHasFact(t, result.Facts, graph.EdgeImports, "uid://enemy123")
	assertHasFact(t, result.Facts, graph.EdgeCalls, "actors/enemy.attack")
	assertHasFact(t, result.Facts, graph.EdgeReadsConfig, "GAME_MODE")
	assertHasFactKind(t, result.Facts, graph.EdgeAssigns)
	assertHasFactKind(t, result.Facts, graph.EdgePasses)
	assertHasFactKind(t, result.Facts, graph.EdgeReturns)
	assertHasFactKind(t, result.Facts, graph.EdgePublishes)
	assertHasFactKind(t, result.Facts, graph.EdgeSubscribes)
}

func TestParserSuppressesCorroboratedTrackedGDScriptBinding(t *testing.T) {
	root := t.TempDir()
	writeFile(t, root, "buf.gen.yaml", `version: v2
plugins:
  - local: protoc-gen-gdscript
    out: gen
`)
	writeFile(t, root, "schema.proto", "syntax = \"proto3\"; message Message { string value = 1; }\n")
	content := []byte(`class_name SchemaMessage
extends RefCounted
# Generated by gdproto
# Source: schema.proto
# DO NOT EDIT
func reset() -> void:
	pass
`)
	path := "gen/SchemaMessage.pb.gd"
	writeFile(t, root, path, string(content))
	result, err := gdscriptparser.New().Parse(context.Background(), parserapi.Input{Root: root, Path: path, Content: content, RepoID: "repo:test"})
	if err != nil {
		t.Fatal(err)
	}
	if len(result.Nodes) != 1 || result.Nodes[0].Kind != graph.KindFile || result.Nodes[0].Properties["generator"] != "protoc-gen-gdscript" {
		t.Fatalf("tracked binding was not deduplicated: %#v", result.Nodes)
	}
}

func TestParserExtractsCanonicalProtobufUsageWithoutGeneratedBindings(t *testing.T) {
	root := t.TempDir()
	writeFile(t, root, ".gitignore", "generated/\n")
	writeFile(t, root, "buf.yaml", "version: v2\nmodules:\n  - path: proto\n")
	writeFile(t, root, "buf.gen.yaml", `version: v2
plugins:
  - local: protoc-gen-gdscript
    out: generated
`)
	writeFile(t, root, "proto/envelope.proto", `syntax = "proto3";
package acme.v1;
message Envelope {
  string text = 1;
  repeated string tags = 2;
  Child child = 3;
  oneof payload { string raw = 4; }
}
message Child { string name = 1; }
`)
	content := []byte(`class_name Client extends Middle

class Middle extends AcmeV1EnvelopeEnvelope:
	pass

class Lookalike:
	func set_text(_value: String) -> void:
		pass
	func get_text() -> String:
		return ""
	func to_bytes() -> PackedByteArray:
		return PackedByteArray()

var stored: AcmeV1EnvelopeEnvelope
var ordinary: Node
var assigned_field
var assigned_self
var branch_field
var branch_swapped_field
var missing_else_field
var while_field
var for_field
var match_field
var shadow_field
var compound_field

class Derived extends AcmeV1EnvelopeEnvelope:
	func inherited() -> void:
		set_text("inherited")

class Override extends AcmeV1EnvelopeEnvelope:
	func set_text(_value: String) -> void:
		pass
	func get_child() -> Variant:
		return null
	func helper() -> Variant:
		return null
	func use_override() -> void:
		set_text("local override")
		var child = get_child()
		child.set_name("not a generated child")
		self.set_text("self local override")
		self.get_child().set_text("not an Envelope receiver")
		self.helper().set_text("unresolved Variant receiver")

func use(data: PackedByteArray, typed: AcmeV1EnvelopeEnvelope) -> String:
	var envelope_type = AcmeV1EnvelopeEnvelope
	var message = envelope_type.new()
	message.set_text("hello")
	message.add_tags("tag")
	var child = message.new_child()
	child.set_name("nested")
	var nested_name = message.get_child().get_name()
	if typed.has_raw():
		var raw = typed.get_raw()
		typed.set_raw(raw)
	var assigned
	assigned = typed
	var copied = assigned.get_text()
	var encoded = assigned.to_bytes()
	var decoded = AcmeV1EnvelopeEnvelope.from_bytes(data)
	decoded.set_text(copied)
	return nested_name

func forbidden(dynamic, variant: Variant, local: Lookalike) -> void:
	dynamic.set_text("unknown")
	variant.get_text()
	local.set_text("local")
	local.get_text()
	local.to_bytes()

func shadowed(AcmeV1EnvelopeEnvelope: Variant, data: PackedByteArray) -> void:
	var decoded = AcmeV1EnvelopeEnvelope.from_bytes(data)
	decoded.set_text("shadowed")

func self_qualified() -> void:
	self.stored.set_text("stored")

func self_shadowed(ordinary: AcmeV1EnvelopeEnvelope) -> void:
	self.ordinary.set_text("field remains Node")

func assigned_fields(data: PackedByteArray) -> void:
	assigned_field = AcmeV1EnvelopeEnvelope.from_bytes(data)
	self.assigned_field.set_text("bare assignment, self use")
	self.assigned_self = AcmeV1EnvelopeEnvelope.from_bytes(data)
	assigned_self.set_text("self assignment, bare use")

func assigned_field_agreed(cond: bool, data: PackedByteArray) -> void:
	if cond:
		self.assigned_field = AcmeV1EnvelopeEnvelope.from_bytes(data)
	else:
		self.assigned_field = AcmeV1EnvelopeEnvelope.from_bytes(data)
	self.assigned_field.set_text("field proven on every branch")

func uncertain_fields(cond: bool, dynamic, data: PackedByteArray, items: Array) -> void:
	if cond:
		self.branch_field = dynamic
	else:
		self.branch_field = AcmeV1EnvelopeEnvelope.from_bytes(data)
	self.branch_field.set_text("branches disagree")
	if cond:
		self.branch_swapped_field = AcmeV1EnvelopeEnvelope.from_bytes(data)
	else:
		self.branch_swapped_field = dynamic
	self.branch_swapped_field.set_text("swapped branches disagree")
	if cond:
		self.missing_else_field = AcmeV1EnvelopeEnvelope.from_bytes(data)
	self.missing_else_field.set_text("else path has no proof")
	while items.is_empty():
		self.while_field = AcmeV1EnvelopeEnvelope.from_bytes(data)
	self.while_field.set_text("loop may not run")
	for item in items:
		self.for_field = AcmeV1EnvelopeEnvelope.from_bytes(data)
	self.for_field.set_text("iteration may not run")
	match items.size():
		1:
			self.match_field = AcmeV1EnvelopeEnvelope.from_bytes(data)
	self.match_field.set_text("pattern may not match")
	var shadow_field
	shadow_field = AcmeV1EnvelopeEnvelope.from_bytes(data)
	self.shadow_field.set_text("local assignment must not prove field")
	self.compound_field += AcmeV1EnvelopeEnvelope.from_bytes(data)
	self.compound_field.set_text("compound assignment is not type proof")

func uncertain(cond: bool, dynamic, data: PackedByteArray) -> void:
	var value
	if cond:
		value = dynamic
	else:
		value = AcmeV1EnvelopeEnvelope.from_bytes(data)
	value.set_text("not proven on every branch")

func uncertain_swapped(cond: bool, dynamic, data: PackedByteArray) -> void:
	var value
	if cond:
		value = AcmeV1EnvelopeEnvelope.from_bytes(data)
	else:
		value = dynamic
	value.set_text("still not proven on every branch")

func agreed(cond: bool, data: PackedByteArray) -> void:
	var value
	if cond:
		value = AcmeV1EnvelopeEnvelope.from_bytes(data)
	else:
		value = AcmeV1EnvelopeEnvelope.from_bytes(data)
	value.set_text("proven on every branch")

func uncertain_loops(items: Array, data: PackedByteArray) -> void:
	var while_value
	while items.is_empty():
		while_value = AcmeV1EnvelopeEnvelope.from_bytes(data)
	while_value.set_text("loop may not run")
	var for_value
	for item in items:
		for_value = AcmeV1EnvelopeEnvelope.from_bytes(data)
	for_value.set_text("iteration may not run")
	var match_value
	match items.size():
		1:
			match_value = AcmeV1EnvelopeEnvelope.from_bytes(data)
	match_value.set_text("pattern may not match")

func exhaustive_match(value: int, data: PackedByteArray) -> void:
	var message
	match value:
		1:
			message = AcmeV1EnvelopeEnvelope.from_bytes(data)
		_:
			message = AcmeV1EnvelopeEnvelope.from_bytes(data)
	message.set_text("every arm proves the type")

func inherited_chain() -> void:
	set_text("inherited through inner base")

func shadow_parameter(stored) -> void:
	stored.set_text("untyped parameter")

func shadow_local() -> void:
	var stored
	stored.set_text("untyped local")

func shadow_for(items: Array) -> void:
	for stored in items:
		stored.set_text("untyped loop variable")

func shadow_lambda() -> void:
	var callback = func(stored):
		stored.set_text("untyped lambda parameter")
	callback.call(null)

func shadow_branch(cond: bool) -> void:
	var value: AcmeV1EnvelopeEnvelope
	if cond:
		var value
		value.set_text("untyped branch local")

func invalid_static_accessors() -> void:
	AcmeV1EnvelopeEnvelope.set_text("class object")
	AcmeV1EnvelopeEnvelope.to_bytes()
	var child = AcmeV1EnvelopeEnvelope.get_child()
	child.set_name("unproven return")
`)
	writeFile(t, root, "client.gd", string(content))
	result, err := gdscriptparser.New().Parse(context.Background(), parserapi.Input{
		Root: root, Path: "client.gd", Content: content, Repository: "protobuf-gdscript", RepoID: "repo",
	})
	if err != nil {
		t.Fatal(err)
	}
	useID := findQualifiedNode(t, result.Nodes, graph.KindMethod, "Client.use").ID
	assertProtocolFact(t, result.Facts, useID, graph.EdgeWrites, "acme.v1.Envelope.text", "set")
	assertProtocolFact(t, result.Facts, useID, graph.EdgeWrites, "acme.v1.Envelope.tags", "add")
	assertProtocolFact(t, result.Facts, useID, graph.EdgeWrites, "acme.v1.Envelope.child", "new")
	assertProtocolFact(t, result.Facts, useID, graph.EdgeWrites, "acme.v1.Child.name", "set")
	assertProtocolFact(t, result.Facts, useID, graph.EdgeReads, "acme.v1.Envelope.child", "get")
	assertProtocolFact(t, result.Facts, useID, graph.EdgeReads, "acme.v1.Child.name", "get")
	assertProtocolFact(t, result.Facts, useID, graph.EdgeReads, "acme.v1.Envelope.raw", "has")
	assertProtocolFact(t, result.Facts, useID, graph.EdgeReads, "acme.v1.Envelope.raw", "get")
	assertProtocolFact(t, result.Facts, useID, graph.EdgeWrites, "acme.v1.Envelope.raw", "set")
	assertProtocolFact(t, result.Facts, useID, graph.EdgeEncodes, "acme.v1.Envelope", "to_bytes")
	assertProtocolFact(t, result.Facts, useID, graph.EdgeDecodes, "acme.v1.Envelope", "from_bytes")
	assertHasFact(t, result.Facts, graph.EdgeCalls, "AcmeV1EnvelopeEnvelope.set_text")

	forbiddenID := findQualifiedNode(t, result.Nodes, graph.KindMethod, "Client.forbidden").ID
	shadowedID := findQualifiedNode(t, result.Nodes, graph.KindMethod, "Client.shadowed").ID
	selfQualifiedID := findQualifiedNode(t, result.Nodes, graph.KindMethod, "Client.self_qualified").ID
	derivedID := findQualifiedNode(t, result.Nodes, graph.KindMethod, "Client.Derived.inherited").ID
	selfFact := assertProtocolFact(t, result.Facts, selfQualifiedID, graph.EdgeWrites, "acme.v1.Envelope.text", "set")
	if selfFact.Properties["static_type"] != "AcmeV1EnvelopeEnvelope" {
		t.Fatalf("self-qualified field static type = %q", selfFact.Properties["static_type"])
	}
	derivedFact := assertProtocolFact(t, result.Facts, derivedID, graph.EdgeWrites, "acme.v1.Envelope.text", "set")
	if derivedFact.Properties["static_type"] != "Client.Derived" {
		t.Fatalf("derived receiver static type = %q", derivedFact.Properties["static_type"])
	}
	agreedID := findQualifiedNode(t, result.Nodes, graph.KindMethod, "Client.agreed").ID
	assertProtocolFact(t, result.Facts, agreedID, graph.EdgeWrites, "acme.v1.Envelope.text", "set")
	assignedFieldsID := findQualifiedNode(t, result.Nodes, graph.KindMethod, "Client.assigned_fields").ID
	assertProtocolFactCount(t, result.Facts, assignedFieldsID, graph.EdgeWrites, "acme.v1.Envelope.text", "set", 2)
	assignedFieldAgreedID := findQualifiedNode(t, result.Nodes, graph.KindMethod, "Client.assigned_field_agreed").ID
	assertProtocolFact(t, result.Facts, assignedFieldAgreedID, graph.EdgeWrites, "acme.v1.Envelope.text", "set")
	exhaustiveMatchID := findQualifiedNode(t, result.Nodes, graph.KindMethod, "Client.exhaustive_match").ID
	assertProtocolFact(t, result.Facts, exhaustiveMatchID, graph.EdgeWrites, "acme.v1.Envelope.text", "set")
	inheritedChainID := findQualifiedNode(t, result.Nodes, graph.KindMethod, "Client.inherited_chain").ID
	assertProtocolFact(t, result.Facts, inheritedChainID, graph.EdgeWrites, "acme.v1.Envelope.text", "set")
	uncertainID := findQualifiedNode(t, result.Nodes, graph.KindMethod, "Client.uncertain").ID
	uncertainSwappedID := findQualifiedNode(t, result.Nodes, graph.KindMethod, "Client.uncertain_swapped").ID
	uncertainLoopsID := findQualifiedNode(t, result.Nodes, graph.KindMethod, "Client.uncertain_loops").ID
	uncertainFieldsID := findQualifiedNode(t, result.Nodes, graph.KindMethod, "Client.uncertain_fields").ID
	selfShadowedID := findQualifiedNode(t, result.Nodes, graph.KindMethod, "Client.self_shadowed").ID
	overrideID := findQualifiedNode(t, result.Nodes, graph.KindMethod, "Client.Override.use_override").ID
	negativeMethods := map[string]bool{}
	for _, qualified := range []string{"Client.shadow_parameter", "Client.shadow_local", "Client.shadow_for", "Client.shadow_lambda", "Client.shadow_branch", "Client.invalid_static_accessors"} {
		negativeMethods[findQualifiedNode(t, result.Nodes, graph.KindMethod, qualified).ID] = true
	}
	for _, fact := range result.Facts {
		if (fact.FromID == forbiddenID || fact.FromID == shadowedID || fact.FromID == selfShadowedID || fact.FromID == overrideID || negativeMethods[fact.FromID]) && fact.Properties["protocol"] == "protobuf" {
			t.Fatalf("unproven or local lookalike receiver produced protocol usage: %#v", fact)
		}
		if (fact.FromID == uncertainID || fact.FromID == uncertainSwappedID || fact.FromID == uncertainLoopsID || fact.FromID == uncertainFieldsID) && fact.Kind == graph.EdgeWrites && fact.Properties["protocol"] == "protobuf" {
			t.Fatalf("branch-dependent receiver produced protocol write: %#v", fact)
		}
	}
	assertHasFact(t, result.Facts, graph.EdgeCalls, "Client.Override.set_text")
	assertHasFact(t, result.Facts, graph.EdgeCalls, "Node.set_text")
}

func TestParserInfersForwardFieldThroughGeneratedBase(t *testing.T) {
	root := t.TempDir()
	writeFile(t, root, "buf.gen.yaml", "version: v2\nplugins:\n  - local: protoc-gen-gdscript\n    out: generated\n")
	writeFile(t, root, "envelope.proto", "syntax = \"proto3\"; package acme.v1; message Envelope { string text = 1; }\n")
	content := []byte(`class_name Forward extends AcmeV1EnvelopeEnvelope

func use() -> void:
	cached.set_text("forward")

var cached = from_bytes(PackedByteArray())
`)
	writeFile(t, root, "forward.gd", string(content))
	result, err := gdscriptparser.New().Parse(context.Background(), parserapi.Input{
		Root: root, Path: "forward.gd", Content: content, RepoID: "repo",
	})
	if err != nil {
		t.Fatal(err)
	}
	useID := findQualifiedNode(t, result.Nodes, graph.KindMethod, "Forward.use").ID
	assertProtocolFact(t, result.Facts, useID, graph.EdgeWrites, "acme.v1.Envelope.text", "set")
}

func TestParserRejectsAmbiguousProtobufGDScriptBindings(t *testing.T) {
	root := t.TempDir()
	writeFile(t, root, "buf.yaml", "version: v2\nmodules:\n  - path: proto\n")
	writeFile(t, root, "buf.gen.yaml", "version: v2\nplugins:\n  - local: protoc-gen-gdscript\n    out: generated\n")
	writeFile(t, root, "proto/one/envelope.proto", "syntax = \"proto3\"; package acme.v1; message Envelope { string text = 1; }\n")
	// gdproto's class-name normalization makes acme.v1 and acme_v1 collide.
	writeFile(t, root, "proto/two/envelope.proto", "syntax = \"proto3\"; package acme_v1; message Envelope { string other = 1; }\n")
	content := []byte("class_name Client\nclass Derived extends AcmeV1EnvelopeEnvelope:\n\tfunc use() -> void:\n\t\tset_text(\"ambiguous base\")\nfunc use(typed: AcmeV1EnvelopeEnvelope) -> void:\n\ttyped.set_text(\"first schema\")\n\ttyped.set_other(\"second schema\")\n\tvar inferred = AcmeV1EnvelopeEnvelope.new()\n\tinferred.set_text(\"constructor fallback\")\n")
	writeFile(t, root, "client.gd", string(content))
	result, err := gdscriptparser.New().Parse(context.Background(), parserapi.Input{
		Root: root, Path: "client.gd", Content: content, RepoID: "repo",
	})
	if err != nil {
		t.Fatal(err)
	}
	for _, fact := range result.Facts {
		if fact.Properties["protocol"] == "protobuf" {
			t.Fatalf("ambiguous generated API produced protocol usage: %#v", fact)
		}
	}
	assertHasFact(t, result.Facts, graph.EdgeCalls, "AcmeV1EnvelopeEnvelope.set_text")
	assertHasFact(t, result.Facts, graph.EdgeCalls, "AcmeV1EnvelopeEnvelope.set_other")
	assertHasFact(t, result.Facts, graph.EdgeCalls, "inferred.set_text")
	for _, diagnostic := range result.Diagnostics {
		if strings.Contains(diagnostic.Message, "ambiguous generated Protobuf GDScript API") {
			return
		}
	}
	t.Fatalf("missing ambiguous binding diagnostic: %#v", result.Diagnostics)
}

func TestParserSuppressesProtocolUseInConfiguredGDScriptOutputWithRejectedHeader(t *testing.T) {
	root := t.TempDir()
	writeFile(t, root, "buf.gen.yaml", "version: v2\nplugins:\n  - local: protoc-gen-gdscript\n    out: generated\n")
	writeFile(t, root, "schema.proto", "syntax = \"proto3\"; message Message { string value = 1; }\n")
	content := []byte("class_name SchemaMessage\n# Generated by an unsupported tool\nfunc use(value: SchemaMessage) -> void:\n\tvalue.set_value(\"generated implementation\")\n")
	path := "generated/SchemaMessage.pb.gd"
	writeFile(t, root, path, string(content))
	result, err := gdscriptparser.New().Parse(context.Background(), parserapi.Input{Root: root, Path: path, Content: content, RepoID: "repo"})
	if err != nil {
		t.Fatal(err)
	}
	assertHasFact(t, result.Facts, graph.EdgeCalls, "SchemaMessage.set_value")
	for _, fact := range result.Facts {
		if fact.Properties["protocol"] == "protobuf" {
			t.Fatalf("configured generated implementation produced protocol usage: %#v", fact)
		}
	}
}

func assertProtocolFact(t *testing.T, facts []graph.Fact, fromID string, kind graph.EdgeKind, target, form string) graph.Fact {
	t.Helper()
	for _, fact := range facts {
		if fact.FromID != fromID || fact.Kind != kind || fact.Target != target || fact.Properties["form"] != form {
			continue
		}
		if fact.TargetID == "" || fact.Location.Path == "" || fact.Location.Line == 0 ||
			fact.Properties["protocol"] != "protobuf" || fact.Properties["api"] == "" ||
			fact.Properties["static_type"] == "" || fact.Properties["binding"] == "" ||
			fact.Properties["binding_id"] == "" || fact.Properties["evidence"] != "gdscript_scope" {
			t.Fatalf("protocol fact lost canonical evidence: %#v", fact)
		}
		return fact
	}
	t.Fatalf("missing %s protocol fact from %q to %q with form %q", kind, fromID, target, form)
	return graph.Fact{}
}

func assertProtocolFactCount(t *testing.T, facts []graph.Fact, fromID string, kind graph.EdgeKind, target, form string, want int) {
	t.Helper()
	count := 0
	for _, fact := range facts {
		if fact.FromID == fromID && fact.Kind == kind && fact.Target == target && fact.Properties["form"] == form {
			count++
		}
	}
	if count != want {
		t.Fatalf("%s protocol fact count from %q to %q with form %q = %d, want %d", kind, fromID, target, form, count, want)
	}
}

func TestParserCreatesImplicitScriptClassAndInnerTypes(t *testing.T) {
	content := []byte(`extends Node

enum State { IDLE, RUNNING = 2 }

class Helper extends RefCounted:
	var enabled: bool
	func run() -> void:
		pass

func ready() -> void:
	for child: Node in get_children():
		child.queue_free()
`)
	result, err := gdscriptparser.New().Parse(context.Background(), parserapi.Input{
		Path: "scripts/controller.gd", Content: content, RepoID: "repo:sample",
	})
	if err != nil {
		t.Fatal(err)
	}
	assertHasQualifiedNode(t, result.Nodes, graph.KindClass, "scripts/controller")
	assertHasQualifiedNode(t, result.Nodes, graph.KindClass, "scripts/controller.Helper")
	assertHasNode(t, result.Nodes, graph.KindType, "State")
	assertHasNode(t, result.Nodes, graph.KindVariable, "child")
	assertHasFact(t, result.Facts, graph.EdgeExtends, "Node")
	assertHasFact(t, result.Facts, graph.EdgeExtends, "RefCounted")
}

func TestParserResolvesMembersDeclaredLater(t *testing.T) {
	content := []byte(`class_name Ordered

func start(value: int) -> void:
	later = value
	finished.emit(value)
	finish()

var later: int
signal finished(value: int)
func finish() -> void:
	pass
`)
	result, err := gdscriptparser.New().Parse(context.Background(), parserapi.Input{
		Path: "ordered.gd", Content: content, RepoID: "repo:sample",
	})
	if err != nil {
		t.Fatal(err)
	}
	assertHasFact(t, result.Facts, graph.EdgeCalls, "Ordered.finish")
	assertHasFactKind(t, result.Facts, graph.EdgeAssigns)
	assertHasFactKind(t, result.Facts, graph.EdgePublishes)
}

func TestParserReturnsPositionedSyntaxErrors(t *testing.T) {
	_, err := gdscriptparser.New().Parse(context.Background(), parserapi.Input{
		Path: "broken.gd", Content: []byte("func broken(\n"),
	})
	if err == nil {
		t.Fatal("expected parse error")
	}
	if !strings.Contains(err.Error(), "broken.gd:") {
		t.Fatalf("error does not contain filename and position: %v", err)
	}
}

func TestParserSupportsGDScriptFilesCaseInsensitively(t *testing.T) {
	parser := gdscriptparser.New()
	if !parser.Supports("player.gd") || !parser.Supports("PLAYER.GD") || parser.Supports("player.gdshader") {
		t.Fatal("unexpected GDScript extension support")
	}
}

func TestParserLinksProjectSettingsAndInputActions(t *testing.T) {
	result, err := gdscriptparser.New().Parse(context.Background(), parserapi.Input{
		Path: "scripts/settings.gd", RepoID: "repo:sample", Content: []byte(`class_name Settings

func load_main_scene() -> String:
	if Input.is_action_just_pressed("jump"):
		return "jump"
	return ProjectSettings.get_setting("application/run/main_scene")
`),
	})
	if err != nil {
		t.Fatal(err)
	}
	assertHasFact(t, result.Facts, graph.EdgeReadsConfig, "application/run/main_scene")
	assertHasFact(t, result.Facts, graph.EdgeReadsConfig, "input/jump")
}

func TestParserLinksNodePathAndRuntimeNodeLookups(t *testing.T) {
	result, err := gdscriptparser.New().Parse(context.Background(), parserapi.Input{
		Path: "scripts/menu.gd", RepoID: "repo:sample", Content: []byte(`class_name Menu

func bind_nodes() -> void:
	var unique_button = %StartButton
	var status = $Panel/Status
	get_node("Panel/StartButton")
	get_node_or_null(^"Panel/Optional")
	has_node("Panel/Status:visible")
`),
	})
	if err != nil {
		t.Fatal(err)
	}
	assertHasFactWithProperty(t, result.Facts, graph.EdgeReferences, "StartButton", "unique", "true")
	assertHasFactWithProperty(t, result.Facts, graph.EdgeReferences, "StartButton", "lookup", "get_node")
	assertHasFactWithProperty(t, result.Facts, graph.EdgeReferences, "Status", "form", "node_path")
	assertHasFactWithProperty(t, result.Facts, graph.EdgeReferences, "Optional", "lookup", "get_node_or_null")
	assertHasFactWithProperty(t, result.Facts, graph.EdgeReferences, "Status", "lookup", "has_node")
}

func assertHasFactKind(t *testing.T, facts []graph.Fact, kind graph.EdgeKind) {
	t.Helper()
	for _, fact := range facts {
		if fact.Kind == kind {
			return
		}
	}
	t.Fatalf("missing %s fact; got %#v", kind, facts)
}

func assertHasNode(t *testing.T, nodes []graph.Node, kind graph.NodeKind, name string) {
	t.Helper()
	for _, node := range nodes {
		if node.Kind == kind && node.Name == name {
			return
		}
	}
	t.Fatalf("missing %s node %q; got %#v", kind, name, nodes)
}

func assertHasQualifiedNode(t *testing.T, nodes []graph.Node, kind graph.NodeKind, qualified string) {
	t.Helper()
	for _, node := range nodes {
		if node.Kind == kind && node.QualifiedName == qualified {
			return
		}
	}
	t.Fatalf("missing %s node %q; got %#v", kind, qualified, nodes)
}

func assertHasFact(t *testing.T, facts []graph.Fact, kind graph.EdgeKind, target string) {
	t.Helper()
	for _, fact := range facts {
		if fact.Kind == kind && fact.Target == target {
			return
		}
	}
	t.Fatalf("missing %s fact to %q; got %#v", kind, target, facts)
}

func assertHasFactWithProperty(t *testing.T, facts []graph.Fact, kind graph.EdgeKind, target, key, value string) {
	t.Helper()
	for _, fact := range facts {
		if fact.Kind == kind && fact.Target == target && fact.Properties[key] == value {
			return
		}
	}
	t.Fatalf("missing %s fact to %q with %s=%q; got %#v", kind, target, key, value, facts)
}

func TestParserDeclaresScriptModuleForResourceIdentity(t *testing.T) {
	result, err := gdscriptparser.New().Parse(context.Background(), parserapi.Input{
		Path: "scripts/player.gd", Content: []byte("class_name Player extends Node\n"),
		Repository: "sample", RepoID: "repo:sample",
	})
	if err != nil {
		t.Fatal(err)
	}
	module := findQualifiedNode(t, result.Nodes, graph.KindModule, "scripts/player")
	if module.Properties["form"] != "script" {
		t.Fatalf("script module properties = %#v", module.Properties)
	}
	class := findQualifiedNode(t, result.Nodes, graph.KindClass, "Player")
	for _, fact := range result.Facts {
		if fact.Kind == graph.EdgeDeclares && fact.FromID == module.ID && fact.TargetID == class.ID {
			return
		}
	}
	t.Fatalf("script module does not declare its class; got %#v", result.Facts)
}

func TestParserResolvesAutoloadUsesFromProjectDeclarations(t *testing.T) {
	root := t.TempDir()
	writeFile(t, root, "client/project.godot", `config_version=5

[autoload]
Game="*res://scripts/game.gd"
Menu="*res://scenes/menu.tscn"
Disabled="res://scripts/disabled.gd"
Twice="*res://scripts/a.gd"
Twice="*res://scripts/b.gd"
`)
	content := []byte(`extends Node

func ready() -> void:
	Game.start()
	var scene = Menu
	Disabled.start()
	Twice.start()
	Unknown.start()
`)
	result, err := gdscriptparser.New().Parse(context.Background(), parserapi.Input{
		Root: root, Path: "client/scripts/hud.gd", Content: content, Repository: "sample", RepoID: "repo:sample",
	})
	if err != nil {
		t.Fatal(err)
	}
	call := findFactWithTarget(t, result.Facts, graph.EdgeReferences, "godot:autoload:client/project.godot:Game")
	if call.TargetKind != graph.KindGodotAutoload || call.Properties["form"] != "autoload_call" ||
		call.Properties["member"] != "start" {
		t.Fatalf("autoload call fact = %#v", call)
	}
	reference := findFactWithTarget(t, result.Facts, graph.EdgeReferences, "godot:autoload:client/project.godot:Menu")
	if reference.Properties["form"] != "autoload_reference" {
		t.Fatalf("autoload reference fact = %#v", reference)
	}
	// A conflicting declaration, an undeclared name, and an autoload Godot does
	// not expose as a global singleton must all resolve nothing.
	for _, name := range []string{"Twice", "Unknown", "Disabled"} {
		for _, fact := range result.Facts {
			if strings.HasSuffix(fact.Target, ":"+name) && strings.HasPrefix(fact.Target, "godot:autoload:") {
				t.Fatalf("autoload %q must not resolve: %#v", name, fact)
			}
		}
	}
}

func writeFile(t *testing.T, root, name, content string) {
	t.Helper()
	path := filepath.Join(root, filepath.FromSlash(name))
	if err := os.MkdirAll(filepath.Dir(path), 0o755); err != nil {
		t.Fatal(err)
	}
	if err := os.WriteFile(path, []byte(content), 0o644); err != nil {
		t.Fatal(err)
	}
}

func findQualifiedNode(t *testing.T, nodes []graph.Node, kind graph.NodeKind, qualified string) graph.Node {
	t.Helper()
	for _, node := range nodes {
		if node.Kind == kind && node.QualifiedName == qualified {
			return node
		}
	}
	t.Fatalf("missing %s node %q; got %#v", kind, qualified, nodes)
	return graph.Node{}
}

func findFactWithTarget(t *testing.T, facts []graph.Fact, kind graph.EdgeKind, target string) graph.Fact {
	t.Helper()
	for _, fact := range facts {
		if fact.Kind == kind && fact.Target == target {
			return fact
		}
	}
	t.Fatalf("missing %s fact to %q; got %#v", kind, target, facts)
	return graph.Fact{}
}

// TestParserKeepsProjectEscapingPreloadsUnresolved covers the project boundary on
// the script side: a preload that traverses out of its own project must not
// resolve into a sibling project.
func TestParserKeepsProjectEscapingPreloadsUnresolved(t *testing.T) {
	root := t.TempDir()
	writeFile(t, root, "client/project.godot", "config_version=5\n")
	writeFile(t, root, "tools/probe/project.godot", "config_version=5\n")

	result, err := gdscriptparser.New().Parse(context.Background(), parserapi.Input{
		Root: root, Path: "client/scripts/hud.gd", Repository: "sample", RepoID: "repo:sample",
		Content: []byte("extends Node\n" +
			"const Inside = preload('res://scripts/inside.gd')\n" +
			"const Outside = preload('res://../tools/probe/scripts/probe.gd')\n"),
	})
	if err != nil {
		t.Fatal(err)
	}
	assertHasFact(t, result.Facts, graph.EdgeImports, "client/scripts/inside")
	for _, fact := range result.Facts {
		if strings.HasPrefix(fact.Target, "tools/probe") {
			t.Fatalf("a preload escaped its project: %#v", fact)
		}
		if fact.Kind == graph.EdgeImports && fact.Target == "" {
			t.Fatalf("an unresolvable preload emitted an empty target: %#v", fact)
		}
	}
}

// TestParserLinksLiteralInputActionUses covers the typed action vocabulary: a
// literal action name on a recognized action API resolves to the project-scoped
// action, a computed name resolves nothing, and a literal argument that is not an
// action name on an Input call is no longer mistaken for one.
func TestParserLinksLiteralInputActionUses(t *testing.T) {
	root := t.TempDir()
	writeFile(t, root, "client/project.godot", "config_version=5\n\n[input]\njump={\"deadzone\": 0.5, \"events\": []}\n")
	result, err := gdscriptparser.New().Parse(context.Background(), parserapi.Input{
		Root: root, Path: "client/scripts/hud.gd", Repository: "sample", RepoID: "repo:sample",
		Content: []byte(`extends Node

const ACTION = "crouch"

func poll(event: InputEvent) -> void:
	if Input.is_action_just_pressed("jump"):
		pass
	var strength = Input.get_action_strength("attack")
	var lean = Input.get_axis("lean_left", "lean_right")
	if event.is_action_pressed("cancel"):
		pass
	if InputMap.has_action(ACTION):
		pass
	Input.set_custom_mouse_cursor("res://art/cursor.png")
	if is_action_bar_visible():
		pass

func is_action_bar_visible() -> bool:
	return true
`),
	})
	if err != nil {
		t.Fatal(err)
	}
	for _, testCase := range []struct{ action, form string }{
		{action: "jump", form: "query"},
		{action: "attack", form: "query"},
		{action: "lean_left", form: "query"},
		{action: "lean_right", form: "query"},
		{action: "cancel", form: "query"},
	} {
		target := "godot:input_action:client/project.godot:" + testCase.action
		fact := findFactWithTarget(t, result.Facts, graph.EdgeUsesInputAction, target)
		if fact.TargetKind != graph.KindGodotInputAction || fact.Properties["form"] != testCase.form ||
			fact.Properties["action"] != testCase.action {
			t.Fatalf("input action fact = %#v", fact)
		}
		// The generic configuration reader stays, so config catalogs keep the
		// same evidence they had before actions became their own kind.
		assertHasFact(t, result.Facts, graph.EdgeReadsConfig, "input/"+testCase.action)
	}
	for _, fact := range result.Facts {
		if fact.Kind == graph.EdgeUsesInputAction && fact.Target == "" {
			t.Fatalf("an action use emitted an empty target: %#v", fact)
		}
		if fact.Kind != graph.EdgeUsesInputAction {
			continue
		}
		switch fact.Properties["action"] {
		case "crouch":
			t.Fatalf("a computed action name must resolve nothing: %#v", fact)
		case "res://art/cursor.png":
			t.Fatalf("a non-action argument must not become an action: %#v", fact)
		}
	}
	for _, fact := range result.Facts {
		if fact.Kind == graph.EdgeReadsConfig && strings.HasPrefix(fact.Target, "input/res://") {
			t.Fatalf("a cursor path must not be read as an input action: %#v", fact)
		}
	}
}

// TestParserLinksLiteralGroupOperations covers the node-group vocabulary:
// membership, membership tests, lookups, and dispatches each keep their operation
// form, a dispatch records its method as evidence without inventing a handler, and
// a computed group name resolves nothing.
func TestParserLinksLiteralGroupOperations(t *testing.T) {
	root := t.TempDir()
	writeFile(t, root, "client/project.godot", "config_version=5\n\n[global_group]\nenemies=\"Hostile\"\n")
	result, err := gdscriptparser.New().Parse(context.Background(), parserapi.Input{
		Root: root, Path: "client/scripts/spawner.gd", Repository: "sample", RepoID: "repo:sample",
		Content: []byte(`extends Node

const OPT_OUT = "opted_out"

func wire(other: Node) -> void:
	add_to_group("enemies")
	other.add_to_group("damageable")
	other.remove_from_group("damageable")
	if other.is_in_group("enemies"):
		pass
	var all = get_tree().get_nodes_in_group("enemies")
	get_tree().call_group("enemies", "die")
	get_tree().notify_group("enemies", 1)
	other.add_to_group(OPT_OUT)
`),
	})
	if err != nil {
		t.Fatal(err)
	}
	enemies := "godot:node_group:client/project.godot:enemies"
	damageable := "godot:node_group:client/project.godot:damageable"
	for _, testCase := range []struct {
		kind   graph.EdgeKind
		target string
		form   string
	}{
		{kind: graph.EdgeInGroup, target: enemies, form: "add"},
		{kind: graph.EdgeInGroup, target: damageable, form: "add"},
		{kind: graph.EdgeInGroup, target: damageable, form: "remove"},
		{kind: graph.EdgeUsesGroup, target: enemies, form: "membership_test"},
		{kind: graph.EdgeUsesGroup, target: enemies, form: "lookup"},
		{kind: graph.EdgeUsesGroup, target: enemies, form: "call"},
		{kind: graph.EdgeUsesGroup, target: enemies, form: "notify"},
	} {
		assertHasFactWithProperty(t, result.Facts, testCase.kind, testCase.target, "form", testCase.form)
	}
	// A membership test is never membership evidence.
	for _, fact := range result.Facts {
		if fact.Kind == graph.EdgeInGroup && fact.Properties["form"] == "membership_test" {
			t.Fatalf("is_in_group must not assert membership: %#v", fact)
		}
		if fact.Kind == graph.EdgeUsesGroup || fact.Kind == graph.EdgeInGroup {
			if fact.Target == "" {
				t.Fatalf("a group operation emitted an empty target: %#v", fact)
			}
			if fact.TargetKind != graph.KindGodotNodeGroup {
				t.Fatalf("a group operation must target a node group: %#v", fact)
			}
			if fact.Properties["group"] == "" {
				t.Fatalf("a group operation is missing its name evidence: %#v", fact)
			}
		}
		if strings.HasSuffix(fact.Target, ":opted_out") {
			t.Fatalf("a computed group name must resolve nothing: %#v", fact)
		}
	}
	// A group dispatch keeps its literal method as evidence and never becomes a
	// call edge to a guessed receiver.
	assertHasFactWithProperty(t, result.Facts, graph.EdgeUsesGroup, enemies, "method", "die")
	for _, fact := range result.Facts {
		if fact.Kind == graph.EdgeCalls && fact.Target == "die" {
			t.Fatalf("a group dispatch must not guess a handler: %#v", fact)
		}
	}
}

// TestParserRoutesLiteralSignalConnections covers signal routing from scripts:
// connect subscribes and names its handler, emit publishes, and disconnect and
// is_connected are routing evidence that never become subscriptions.
func TestParserRoutesLiteralSignalConnections(t *testing.T) {
	result, err := gdscriptparser.New().Parse(context.Background(), parserapi.Input{
		Path: "scripts/hud.gd", Repository: "sample", RepoID: "repo:sample",
		Content: []byte(`class_name Hud extends Node

signal ready_changed(value: bool)

func wire() -> void:
	ready_changed.connect(on_ready_changed)
	ready_changed.emit(true)
	if ready_changed.is_connected(on_ready_changed):
		ready_changed.disconnect(on_ready_changed)
	emit_signal("ready_changed", false)

func on_ready_changed(_value: bool) -> void:
	pass
`),
	})
	if err != nil {
		t.Fatal(err)
	}
	event := findQualifiedNode(t, result.Nodes, graph.KindEvent, "Hud.ready_changed")
	handled := false
	for _, fact := range result.Facts {
		if fact.Kind == graph.EdgeHandledBy && fact.FromID == event.ID &&
			fact.Target == "Hud.on_ready_changed" && fact.Properties["form"] == "connect" {
			handled = true
		}
		if fact.Kind == graph.EdgeSubscribes && fact.Properties["form"] != "connect" {
			t.Fatalf("only a connect may subscribe: %#v", fact)
		}
	}
	if !handled {
		t.Fatalf("a literal connect must name its handler; got %#v", result.Facts)
	}
	// The route's destination is recorded on the routing fact as well, which is
	// the only place it can live when the signal's owner is another file.
	subscribed := false
	for _, fact := range result.Facts {
		if fact.Kind == graph.EdgeSubscribes && fact.Properties["handler"] == "Hud.on_ready_changed" {
			subscribed = true
		}
	}
	if !subscribed {
		t.Fatalf("a connect must record its handler as evidence; got %#v", result.Facts)
	}
	for _, form := range []string{"signal_disconnect", "signal_connection_test"} {
		found := false
		for _, fact := range result.Facts {
			if fact.Kind == graph.EdgeReferences && fact.TargetID == event.ID &&
				fact.Properties["form"] == form {
				found = true
			}
		}
		if !found {
			t.Fatalf("missing %s evidence; got %#v", form, result.Facts)
		}
	}
	publishes := 0
	for _, fact := range result.Facts {
		if fact.Kind == graph.EdgePublishes && fact.TargetID == event.ID {
			publishes++
			if fact.Properties["form"] != "emit" {
				t.Fatalf("a publish must record its form: %#v", fact)
			}
		}
	}
	if publishes != 2 {
		t.Fatalf("expected both emit forms to publish, got %d", publishes)
	}
}

// TestParserRecordsHandlerWhenSignalOwnerIsAnotherFile is the case the smoke run
// exposed: nearly every real connect names a signal another file declares, so no
// handled_by edge is emitted with a named source when this parser cannot see the
// declaration. Storage, rather than the parser, decides whether that source is
// uniquely declared.
func TestParserRecordsHandlerWhenSignalOwnerIsAnotherFile(t *testing.T) {
	result, err := gdscriptparser.New().Parse(context.Background(), parserapi.Input{
		Path: "scripts/kit.gd", Repository: "sample", RepoID: "repo:sample",
		Content: []byte(`class_name Kit extends Node

var _backend: Backend

func wire() -> void:
	_backend.sign_in_success.connect(_on_sign_in)
	_backend.sign_in_failed.connect(func(): pass)

func _on_sign_in() -> void:
	pass
`),
	})
	if err != nil {
		t.Fatal(err)
	}
	routed := findFactWithTarget(t, result.Facts, graph.EdgeSubscribes, "Backend.sign_in_success")
	if routed.Properties["form"] != "connect" || routed.Properties["handler"] != "Kit._on_sign_in" {
		t.Fatalf("cross-file connect fact = %#v", routed)
	}
	lambda := findFactWithTarget(t, result.Facts, graph.EdgeSubscribes, "Backend.sign_in_failed")
	if _, ok := lambda.Properties["handler"]; ok {
		t.Fatalf("a lambda proves no method; got %#v", lambda)
	}
	handled := findFactWithTarget(t, result.Facts, graph.EdgeHandledBy, "Kit._on_sign_in")
	if handled.FromID != "" || handled.Source != "Backend.sign_in_success" ||
		handled.SourceKind != graph.KindEvent || handled.Properties["form"] != "connect" {
		t.Fatalf("cross-file handled_by fact = %#v", handled)
	}
	for _, fact := range result.Facts {
		if fact.Kind == graph.EdgeHandledBy && fact.Source == "Backend.sign_in_failed" {
			t.Fatalf("a lambda proves no handler: %#v", fact)
		}
	}
}

// TestParserDoesNotReadANonSignalLiteralAsASignalName covers the ambiguity a
// project can create for itself: a connect(url) of its own must not name an event
// after its argument, and a disconnect on an object whose type is unknown must not
// invent a signal either.
func TestParserDoesNotReadANonSignalLiteralAsASignalName(t *testing.T) {
	result, err := gdscriptparser.New().Parse(context.Background(), parserapi.Input{
		Path: "scripts/socket.gd", Repository: "sample", RepoID: "repo:sample",
		Content: []byte(`class_name Socket extends Node

var _client: WebSocketPeer

func open() -> void:
	_client.connect("wss://example.invalid/stream")
	inherited_signal.emit(42)
	inherited_signal.connect(_on_inherited)

func _on_inherited() -> void:
	pass
`),
	})
	if err != nil {
		t.Fatal(err)
	}
	for _, fact := range result.Facts {
		if fact.TargetKind == graph.KindEvent && strings.Contains(fact.Target, "://") {
			t.Fatalf("a URL must never become a signal: %#v", fact)
		}
	}
	// Nor does the receiver become one: a literal that can be neither a Callable
	// nor a signal name is proof this is not a signal connection, so the call
	// stays an ordinary call.
	for _, fact := range result.Facts {
		if fact.Kind == graph.EdgeSubscribes && fact.Target != "inherited_signal" {
			t.Fatalf("a connect(url) must not subscribe to anything: %#v", fact)
		}
	}
	assertHasFact(t, result.Facts, graph.EdgeCalls, "WebSocketPeer.connect")
	// A signal a base class declares is emitted and connected by its bare name.
	// It cannot be proved here, so it stays an unresolved event that the graph
	// resolves by name only when exactly one declaration owns it.
	assertHasFactWithProperty(t, result.Facts, graph.EdgePublishes, "inherited_signal", "form", "emit")
	assertHasFactWithProperty(t, result.Facts, graph.EdgeSubscribes, "inherited_signal", "handler",
		"Socket._on_inherited")
}

func TestParserQualifiesLegacyObjectSignalHandlersWithoutGuessing(t *testing.T) {
	result, err := gdscriptparser.New().Parse(context.Background(), parserapi.Input{
		Path: "scripts/kit.gd", Repository: "sample", RepoID: "repo:sample",
		Content: []byte(`class_name Kit extends Node

var _backend: Backend
var _unknown

func wire() -> void:
	_backend.connect("ready", _on_ready)
	_unknown.connect("ready", _on_ready)

func _on_ready() -> void:
	pass
`),
	})
	if err != nil {
		t.Fatal(err)
	}
	want := 0
	for _, fact := range result.Facts {
		if fact.Kind != graph.EdgeHandledBy {
			continue
		}
		want++
		if fact.Source != "Backend.ready" || fact.SourceKind != graph.KindEvent ||
			fact.Target != "Kit._on_ready" {
			t.Fatalf("legacy Object.connect handled_by fact = %#v", fact)
		}
	}
	if want != 1 {
		t.Fatalf("legacy Object.connect handled_by facts = %d, want 1; got %#v", want, result.Facts)
	}
}

func TestParserRequiresStructuralOwnerForMemberSignalHandlers(t *testing.T) {
	result, err := gdscriptparser.New().Parse(context.Background(), parserapi.Input{
		Path: "scripts/kit.gd", Repository: "sample", RepoID: "repo:sample",
		Content: []byte(`class_name Kit extends Node

var _backend: Backend
var _unknown

func wire() -> void:
	_backend.ready.connect(_on_typed)
	_unknown.ready.connect(_on_unknown)

func _on_typed() -> void:
	pass

func _on_unknown() -> void:
	pass
`),
	})
	if err != nil {
		t.Fatal(err)
	}
	typed := false
	for _, fact := range result.Facts {
		if fact.Kind != graph.EdgeHandledBy {
			continue
		}
		if fact.Target == "Kit._on_unknown" {
			t.Fatalf("untyped member receiver produced handled_by fact %#v", fact)
		}
		if fact.Target != "Kit._on_typed" || fact.Source != "Backend.ready" ||
			fact.SourceKind != graph.KindEvent {
			t.Fatalf("member signal handled_by fact = %#v", fact)
		}
		typed = true
	}
	if !typed {
		t.Fatalf("typed member signal produced no handled_by fact: %#v", result.Facts)
	}
}

// TestParserKeepsLocallyDeclaredActionMethodsOutOfTheVocabulary covers both
// spellings of a call on this object. A script is free to declare its own
// is_action_pressed, and neither the bare nor the self-qualified call to it
// involves a Godot input API, so neither may produce a typed action edge.
func TestParserKeepsLocallyDeclaredActionMethodsOutOfTheVocabulary(t *testing.T) {
	root := t.TempDir()
	writeFile(t, root, "client/project.godot", "config_version=5\n\n[input]\njump={\"deadzone\": 0.5, \"events\": []}\n")
	result, err := gdscriptparser.New().Parse(context.Background(), parserapi.Input{
		Root: root, Path: "client/scripts/pane.gd", Repository: "sample", RepoID: "repo:sample",
		Content: []byte(`class_name Pane extends Control

func poll() -> void:
	if is_action_pressed("jump"):
		pass
	if self.is_action_pressed("jump"):
		pass
	if Pane.is_action_pressed("jump"):
		pass
	if add_to_group("enemies"):
		pass
	if self.add_to_group("enemies"):
		pass

func is_action_pressed(_name: String) -> bool:
	return false

func add_to_group(_name: String) -> bool:
	return false
`),
	})
	if err != nil {
		t.Fatal(err)
	}
	for _, fact := range result.Facts {
		switch fact.Kind {
		case graph.EdgeUsesInputAction, graph.EdgeInGroup, graph.EdgeUsesGroup:
			t.Fatalf("a locally declared method must not produce a Godot interaction: %#v", fact)
		case graph.EdgeReadsConfig:
			if strings.HasPrefix(fact.Target, "input/") {
				t.Fatalf("a locally declared method must not read an input action: %#v", fact)
			}
		}
	}
}

// TestParserResolvesActionQueriesOnInputEventReceivers covers the InputEvent
// action-query methods. is_action is an InputEvent method rather than an Input or
// InputMap one, so requiring an Input receiver discarded correct code.
func TestParserResolvesActionQueriesOnInputEventReceivers(t *testing.T) {
	root := t.TempDir()
	writeFile(t, root, "client/project.godot", "config_version=5\n")
	result, err := gdscriptparser.New().Parse(context.Background(), parserapi.Input{
		Root: root, Path: "client/scripts/input.gd", Repository: "sample", RepoID: "repo:sample",
		Content: []byte(`extends Node

func _input(event: InputEvent) -> void:
	if event.is_action("ui_accept"):
		pass
	if event.is_action_pressed("ui_cancel"):
		pass
	if event.is_action_released("ui_left"):
		pass
	var strength = event.get_action_strength("ui_right")
`),
	})
	if err != nil {
		t.Fatal(err)
	}
	for _, action := range []string{"ui_accept", "ui_cancel", "ui_left", "ui_right"} {
		fact := findFactWithTarget(t, result.Facts, graph.EdgeUsesInputAction,
			"godot:input_action:client/project.godot:"+action)
		if fact.Properties["form"] != "query" || fact.Properties["receiver"] != "InputEvent" {
			t.Fatalf("InputEvent action query fact = %#v", fact)
		}
		assertHasFact(t, result.Facts, graph.EdgeReadsConfig, "input/"+action)
	}
}

// TestParserSourcesCrossFileConnectionsAtTheirHandler preserves the traversal
// added before named fact sources existed: the subscribes route remains sourced
// at the handler this script declares rather than at the statement that wired
// it, even though handled_by can now express the signal-to-handler direction.
func TestParserSourcesCrossFileConnectionsAtTheirHandler(t *testing.T) {
	result, err := gdscriptparser.New().Parse(context.Background(), parserapi.Input{
		Path: "scripts/kit.gd", Repository: "sample", RepoID: "repo:sample",
		Content: []byte(`class_name Kit extends Node

var _backend: Backend

func wire() -> void:
	_backend.sign_in_success.connect(_on_sign_in)
	_backend.sign_in_failed.connect(func(): pass)

func _on_sign_in() -> void:
	pass
`),
	})
	if err != nil {
		t.Fatal(err)
	}
	handler := findQualifiedNode(t, result.Nodes, graph.KindMethod, "Kit._on_sign_in")
	routed := findFactWithTarget(t, result.Facts, graph.EdgeSubscribes, "Backend.sign_in_success")
	if routed.FromID != handler.ID {
		t.Fatalf("a resolved handler must source the route: %#v", routed)
	}
	if routed.Properties["handler"] != "Kit._on_sign_in" || routed.Properties["site"] != "Kit.wire" {
		t.Fatalf("the route lost its handler or its call site: %#v", routed)
	}
	// A lambda proves no method, so the route stays at the wiring statement.
	wire := findQualifiedNode(t, result.Nodes, graph.KindMethod, "Kit.wire")
	lambda := findFactWithTarget(t, result.Facts, graph.EdgeSubscribes, "Backend.sign_in_failed")
	if lambda.FromID != wire.ID {
		t.Fatalf("an unprovable handler must leave the route at its call site: %#v", lambda)
	}
	if _, ok := lambda.Properties["handler"]; ok {
		t.Fatalf("a lambda proves no method; got %#v", lambda)
	}
}

// TestParserRefusesActionQueriesOnKnownNonInputReceivers pins the receiver rule
// and, just as importantly, its boundary. A receiver the type table knows to be
// something other than an input class is not a Godot input query, so nothing is
// emitted. A receiver whose type is unknown keeps emitting, because untyped
// parameters are pervasive in GDScript and refusing them would destroy most real
// recall - a deliberate decision this test exists to keep from being quietly
// tightened later.
func TestParserRefusesActionQueriesOnKnownNonInputReceivers(t *testing.T) {
	root := t.TempDir()
	writeFile(t, root, "client/project.godot", "config_version=5\n")
	result, err := gdscriptparser.New().Parse(context.Background(), parserapi.Input{
		Root: root, Path: "client/scripts/pad.gd", Repository: "sample", RepoID: "repo:sample",
		Content: []byte(`class_name Pad extends Node

class LocalEvent extends InputEventKey:
	var tag: int

var _gamepad: Gamepad
var _local: LocalEvent

func poll(typed: InputEvent, untyped) -> void:
	if _gamepad.is_action("refused_known"):
		pass
	if _gamepad.is_action_pressed("refused_family"):
		pass
	var refused_strength = _gamepad.get_action_strength("refused_strength")
	if typed.is_action("kept_typed"):
		pass
	if untyped.is_action("kept_untyped"):
		pass
	if _local.is_action("kept_local_subclass"):
		pass
`),
	})
	if err != nil {
		t.Fatal(err)
	}
	for _, action := range []string{"refused_known", "refused_family", "refused_strength"} {
		for _, fact := range result.Facts {
			if fact.Kind == graph.EdgeUsesInputAction && fact.Properties["action"] == action {
				t.Fatalf("a known non-input receiver must not produce an action edge: %#v", fact)
			}
			if fact.Kind == graph.EdgeReadsConfig && fact.Target == "input/"+action {
				t.Fatalf("a known non-input receiver must not read an input action: %#v", fact)
			}
		}
	}
	for _, action := range []string{"kept_typed", "kept_untyped", "kept_local_subclass"} {
		findFactWithTarget(t, result.Facts, graph.EdgeUsesInputAction,
			"godot:input_action:client/project.godot:"+action)
		assertHasFact(t, result.Facts, graph.EdgeReadsConfig, "input/"+action)
	}
}
