// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: candidates.sql

package sqlcgen

import (
	"context"
)

const listSemanticCandidateNodes = `-- name: ListSemanticCandidateNodes :many
SELECT id, kind, name, qualified_name, language, path, line, column_no, end_line, properties, owner_file, external, name_folded, qualified_name_folded FROM nodes
WHERE external = 0
  AND kind IN ('function', 'method', 'type', 'class', 'interface', 'endpoint')
ORDER BY qualified_name, id
`

func (q *Queries) ListSemanticCandidateNodes(ctx context.Context) ([]Node, error) {
	rows, err := q.query(ctx, q.listSemanticCandidateNodesStmt, listSemanticCandidateNodes)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Node{}
	for rows.Next() {
		var i Node
		if err := rows.Scan(
			&i.ID,
			&i.Kind,
			&i.Name,
			&i.QualifiedName,
			&i.Language,
			&i.Path,
			&i.Line,
			&i.ColumnNo,
			&i.EndLine,
			&i.Properties,
			&i.OwnerFile,
			&i.External,
			&i.NameFolded,
			&i.QualifiedNameFolded,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
