// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: dirty.sql

package sqlcgen

import (
	"context"
)

const clearDirtyNodes = `-- name: ClearDirtyNodes :exec
DELETE FROM dirty_nodes
`

func (q *Queries) ClearDirtyNodes(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, clearDirtyNodes)
	return err
}

const clearDirtyOwners = `-- name: ClearDirtyOwners :exec
DELETE FROM dirty_owners
`

func (q *Queries) ClearDirtyOwners(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, clearDirtyOwners)
	return err
}

const clearDirtyTargets = `-- name: ClearDirtyTargets :exec
DELETE FROM dirty_targets
`

func (q *Queries) ClearDirtyTargets(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, clearDirtyTargets)
	return err
}

const markDirtyNode = `-- name: MarkDirtyNode :exec
INSERT OR IGNORE INTO dirty_nodes(node_id) VALUES (?)
`

func (q *Queries) MarkDirtyNode(ctx context.Context, nodeID string) error {
	_, err := q.db.ExecContext(ctx, markDirtyNode, nodeID)
	return err
}

const markDirtyOwner = `-- name: MarkDirtyOwner :exec
INSERT OR IGNORE INTO dirty_owners(owner_file) VALUES (?)
`

func (q *Queries) MarkDirtyOwner(ctx context.Context, ownerFile string) error {
	_, err := q.db.ExecContext(ctx, markDirtyOwner, ownerFile)
	return err
}

const markDirtyTarget = `-- name: MarkDirtyTarget :exec
INSERT OR IGNORE INTO dirty_targets(target, target_kind) VALUES (?, ?)
`

type MarkDirtyTargetParams struct {
	Target     string `json:"target"`
	TargetKind string `json:"target_kind"`
}

func (q *Queries) MarkDirtyTarget(ctx context.Context, arg MarkDirtyTargetParams) error {
	_, err := q.db.ExecContext(ctx, markDirtyTarget, arg.Target, arg.TargetKind)
	return err
}

const markOwnedNamesDirty = `-- name: MarkOwnedNamesDirty :exec
INSERT OR IGNORE INTO dirty_targets(target, target_kind)
SELECT nodes.name, nodes.kind FROM nodes WHERE nodes.owner_file = ?
UNION
SELECT nodes.qualified_name, nodes.kind FROM nodes WHERE nodes.owner_file = ?
`

type MarkOwnedNamesDirtyParams struct {
	OwnerFile   string `json:"owner_file"`
	OwnerFile_2 string `json:"owner_file_2"`
}

func (q *Queries) MarkOwnedNamesDirty(ctx context.Context, arg MarkOwnedNamesDirtyParams) error {
	_, err := q.db.ExecContext(ctx, markOwnedNamesDirty, arg.OwnerFile, arg.OwnerFile_2)
	return err
}

const markOwnedNodesDirty = `-- name: MarkOwnedNodesDirty :exec
INSERT OR IGNORE INTO dirty_nodes(node_id)
SELECT nodes.id FROM nodes WHERE nodes.owner_file = ?
`

func (q *Queries) MarkOwnedNodesDirty(ctx context.Context, ownerFile string) error {
	_, err := q.db.ExecContext(ctx, markOwnedNodesDirty, ownerFile)
	return err
}
