// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: dirty.sql

package sqlcgen

import (
	"context"
)

const clearDirtyNodes = `-- name: ClearDirtyNodes :exec
DELETE FROM dirty_nodes
`

func (q *Queries) ClearDirtyNodes(ctx context.Context) error {
	_, err := q.exec(ctx, q.clearDirtyNodesStmt, clearDirtyNodes)
	return err
}

const clearDirtyOwners = `-- name: ClearDirtyOwners :exec
DELETE FROM dirty_owners
`

func (q *Queries) ClearDirtyOwners(ctx context.Context) error {
	_, err := q.exec(ctx, q.clearDirtyOwnersStmt, clearDirtyOwners)
	return err
}

const clearDirtyTargets = `-- name: ClearDirtyTargets :exec
DELETE FROM dirty_targets
`

func (q *Queries) ClearDirtyTargets(ctx context.Context) error {
	_, err := q.exec(ctx, q.clearDirtyTargetsStmt, clearDirtyTargets)
	return err
}

const clearReconciliationCleanup = `-- name: ClearReconciliationCleanup :exec
DELETE FROM reconciliation_cleanup
`

func (q *Queries) ClearReconciliationCleanup(ctx context.Context) error {
	_, err := q.exec(ctx, q.clearReconciliationCleanupStmt, clearReconciliationCleanup)
	return err
}

const countDirtyFacts = `-- name: CountDirtyFacts :one
SELECT COUNT(*) FROM dirty_facts
`

func (q *Queries) CountDirtyFacts(ctx context.Context) (int64, error) {
	row := q.queryRow(ctx, q.countDirtyFactsStmt, countDirtyFacts)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const deleteDirtyFactBatch = `-- name: DeleteDirtyFactBatch :exec
DELETE FROM dirty_facts
WHERE fact_id IN (
    SELECT fact_id
    FROM dirty_facts INDEXED BY dirty_facts_order
    ORDER BY owner_file, fact_id
    LIMIT ?
)
`

func (q *Queries) DeleteDirtyFactBatch(ctx context.Context, limit int64) error {
	_, err := q.exec(ctx, q.deleteDirtyFactBatchStmt, deleteDirtyFactBatch, limit)
	return err
}

const enqueueDirtyFacts = `-- name: EnqueueDirtyFacts :exec
INSERT OR IGNORE INTO dirty_facts(fact_id, owner_file)
SELECT facts.id, dirty_owners.owner_file
FROM dirty_owners
CROSS JOIN facts INDEXED BY facts_owner
WHERE facts.owner_path_id = (SELECT id FROM paths WHERE paths.path = dirty_owners.owner_file)
UNION ALL
SELECT facts.id, COALESCE(owner_paths.path, '')
FROM dirty_nodes
CROSS JOIN facts INDEXED BY facts_from_id
LEFT JOIN paths AS owner_paths ON owner_paths.id = facts.owner_path_id
WHERE facts.from_id = dirty_nodes.node_id
  AND (
    NOT EXISTS (
      SELECT 1 FROM nodes
      WHERE nodes.id = facts.from_id AND nodes.external = 0
    )
    OR NOT EXISTS (
      SELECT 1 FROM edges
      WHERE edges.fact_id = facts.id AND edges.from_id = facts.from_id
    )
  )
UNION ALL
SELECT facts.id, COALESCE(owner_paths.path, '')
FROM dirty_nodes
CROSS JOIN facts INDEXED BY facts_target_id
LEFT JOIN paths AS owner_paths ON owner_paths.id = facts.owner_path_id
WHERE facts.target_id = dirty_nodes.node_id
UNION ALL
SELECT facts.id, COALESCE(owner_paths.path, '')
FROM dirty_targets
CROSS JOIN facts INDEXED BY facts_source
LEFT JOIN paths AS owner_paths ON owner_paths.id = facts.owner_path_id
WHERE facts.source = dirty_targets.target
  AND (facts.source_kind = '' OR facts.source_kind = dirty_targets.target_kind)
UNION ALL
SELECT facts.id, COALESCE(owner_paths.path, '')
FROM dirty_targets
CROSS JOIN facts INDEXED BY facts_target
LEFT JOIN paths AS owner_paths ON owner_paths.id = facts.owner_path_id
WHERE facts.target = dirty_targets.target
  AND (facts.target_kind = '' OR facts.target_kind = dirty_targets.target_kind)
`

func (q *Queries) EnqueueDirtyFacts(ctx context.Context) error {
	_, err := q.exec(ctx, q.enqueueDirtyFactsStmt, enqueueDirtyFacts)
	return err
}

const markDirtyNode = `-- name: MarkDirtyNode :exec
INSERT OR IGNORE INTO dirty_nodes(node_id) VALUES (?)
`

func (q *Queries) MarkDirtyNode(ctx context.Context, nodeID string) error {
	_, err := q.exec(ctx, q.markDirtyNodeStmt, markDirtyNode, nodeID)
	return err
}

const markDirtyOwner = `-- name: MarkDirtyOwner :exec
INSERT OR IGNORE INTO dirty_owners(owner_file) VALUES (?)
`

func (q *Queries) MarkDirtyOwner(ctx context.Context, ownerFile string) error {
	_, err := q.exec(ctx, q.markDirtyOwnerStmt, markDirtyOwner, ownerFile)
	return err
}

const markDirtyTarget = `-- name: MarkDirtyTarget :exec
INSERT OR IGNORE INTO dirty_targets(target, target_kind) VALUES (?, ?)
`

type MarkDirtyTargetParams struct {
	Target     string `json:"target"`
	TargetKind string `json:"target_kind"`
}

func (q *Queries) MarkDirtyTarget(ctx context.Context, arg MarkDirtyTargetParams) error {
	_, err := q.exec(ctx, q.markDirtyTargetStmt, markDirtyTarget, arg.Target, arg.TargetKind)
	return err
}

const markOwnedNamesDirty = `-- name: MarkOwnedNamesDirty :exec
INSERT OR IGNORE INTO dirty_targets(target, target_kind)
SELECT nodes.name, nodes.kind FROM nodes WHERE nodes.owner_file = ?
UNION
SELECT nodes.qualified_name, nodes.kind FROM nodes WHERE nodes.owner_file = ?
`

type MarkOwnedNamesDirtyParams struct {
	OwnerFile   string `json:"owner_file"`
	OwnerFile_2 string `json:"owner_file_2"`
}

func (q *Queries) MarkOwnedNamesDirty(ctx context.Context, arg MarkOwnedNamesDirtyParams) error {
	_, err := q.exec(ctx, q.markOwnedNamesDirtyStmt, markOwnedNamesDirty, arg.OwnerFile, arg.OwnerFile_2)
	return err
}

const markOwnedNodesDirty = `-- name: MarkOwnedNodesDirty :exec
INSERT OR IGNORE INTO dirty_nodes(node_id)
SELECT nodes.id FROM nodes WHERE nodes.owner_file = ?
`

func (q *Queries) MarkOwnedNodesDirty(ctx context.Context, ownerFile string) error {
	_, err := q.exec(ctx, q.markOwnedNodesDirtyStmt, markOwnedNodesDirty, ownerFile)
	return err
}

const markReconciliationCleanup = `-- name: MarkReconciliationCleanup :exec
INSERT OR IGNORE INTO reconciliation_cleanup(id)
SELECT 1 WHERE EXISTS (SELECT 1 FROM dirty_facts)
`

func (q *Queries) MarkReconciliationCleanup(ctx context.Context) error {
	_, err := q.exec(ctx, q.markReconciliationCleanupStmt, markReconciliationCleanup)
	return err
}

const pruneDirtyFacts = `-- name: PruneDirtyFacts :exec
DELETE FROM dirty_facts
WHERE NOT EXISTS (SELECT 1 FROM facts WHERE facts.id = dirty_facts.fact_id)
`

func (q *Queries) PruneDirtyFacts(ctx context.Context) error {
	_, err := q.exec(ctx, q.pruneDirtyFactsStmt, pruneDirtyFacts)
	return err
}

const reconciliationCleanupPending = `-- name: ReconciliationCleanupPending :one
SELECT EXISTS (SELECT 1 FROM reconciliation_cleanup)
`

func (q *Queries) ReconciliationCleanupPending(ctx context.Context) (bool, error) {
	row := q.queryRow(ctx, q.reconciliationCleanupPendingStmt, reconciliationCleanupPending)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const reconciliationPending = `-- name: ReconciliationPending :one
SELECT EXISTS (
    SELECT 1 FROM dirty_owners
    UNION ALL SELECT 1 FROM dirty_nodes
    UNION ALL SELECT 1 FROM dirty_targets
    UNION ALL SELECT 1 FROM dirty_facts
    UNION ALL SELECT 1 FROM reconciliation_cleanup
)
`

func (q *Queries) ReconciliationPending(ctx context.Context) (bool, error) {
	row := q.queryRow(ctx, q.reconciliationPendingStmt, reconciliationPending)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}
