// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: edges.sql

package sqlcgen

import (
	"context"
)

const countEdges = `-- name: CountEdges :one
SELECT COUNT(*) FROM edges
`

func (q *Queries) CountEdges(ctx context.Context) (int64, error) {
	row := q.queryRow(ctx, q.countEdgesStmt, countEdges)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countEdgesByKind = `-- name: CountEdgesByKind :many
SELECT kind, COUNT(*) AS count FROM edges GROUP BY kind ORDER BY kind
`

type CountEdgesByKindRow struct {
	Kind  string `json:"kind"`
	Count int64  `json:"count"`
}

func (q *Queries) CountEdgesByKind(ctx context.Context) ([]CountEdgesByKindRow, error) {
	rows, err := q.query(ctx, q.countEdgesByKindStmt, countEdgesByKind)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CountEdgesByKindRow{}
	for rows.Next() {
		var i CountEdgesByKindRow
		if err := rows.Scan(&i.Kind, &i.Count); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const deleteAllEdges = `-- name: DeleteAllEdges :exec
DELETE FROM edges
`

func (q *Queries) DeleteAllEdges(ctx context.Context) error {
	_, err := q.exec(ctx, q.deleteAllEdgesStmt, deleteAllEdges)
	return err
}

const deleteEdgesByDirtyFactBatch = `-- name: DeleteEdgesByDirtyFactBatch :exec
DELETE FROM edges
WHERE fact_id IN (
    SELECT fact_id
    FROM dirty_facts INDEXED BY dirty_facts_order
    ORDER BY owner_file, fact_id
    LIMIT ?
)
`

func (q *Queries) DeleteEdgesByDirtyFactBatch(ctx context.Context, limit int64) error {
	_, err := q.exec(ctx, q.deleteEdgesByDirtyFactBatchStmt, deleteEdgesByDirtyFactBatch, limit)
	return err
}

const deleteEdgesByOwnerFacts = `-- name: DeleteEdgesByOwnerFacts :exec
DELETE FROM edges WHERE fact_id IN (SELECT id FROM facts WHERE owner_file = ?)
`

func (q *Queries) DeleteEdgesByOwnerFacts(ctx context.Context, ownerFile string) error {
	_, err := q.exec(ctx, q.deleteEdgesByOwnerFactsStmt, deleteEdgesByOwnerFacts, ownerFile)
	return err
}

const insertEdge = `-- name: InsertEdge :exec
INSERT INTO edges(
    id, fact_id, from_id, to_id, kind, path, line, column_no, end_line, properties
) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
`

type InsertEdgeParams struct {
	ID         string `json:"id"`
	FactID     string `json:"fact_id"`
	FromID     string `json:"from_id"`
	ToID       string `json:"to_id"`
	Kind       string `json:"kind"`
	Path       string `json:"path"`
	Line       int64  `json:"line"`
	ColumnNo   int64  `json:"column_no"`
	EndLine    int64  `json:"end_line"`
	Properties string `json:"properties"`
}

func (q *Queries) InsertEdge(ctx context.Context, arg InsertEdgeParams) error {
	_, err := q.exec(ctx, q.insertEdgeStmt, insertEdge,
		arg.ID,
		arg.FactID,
		arg.FromID,
		arg.ToID,
		arg.Kind,
		arg.Path,
		arg.Line,
		arg.ColumnNo,
		arg.EndLine,
		arg.Properties,
	)
	return err
}

const listEdgesFrom = `-- name: ListEdgesFrom :many
SELECT id, fact_id, from_id, to_id, kind, path, line, column_no, end_line, properties FROM edges WHERE from_id = ? ORDER BY kind, to_id, id
`

func (q *Queries) ListEdgesFrom(ctx context.Context, fromID string) ([]Edge, error) {
	rows, err := q.query(ctx, q.listEdgesFromStmt, listEdgesFrom, fromID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Edge{}
	for rows.Next() {
		var i Edge
		if err := rows.Scan(
			&i.ID,
			&i.FactID,
			&i.FromID,
			&i.ToID,
			&i.Kind,
			&i.Path,
			&i.Line,
			&i.ColumnNo,
			&i.EndLine,
			&i.Properties,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listEdgesTo = `-- name: ListEdgesTo :many
SELECT id, fact_id, from_id, to_id, kind, path, line, column_no, end_line, properties FROM edges WHERE to_id = ? ORDER BY kind, from_id, id
`

func (q *Queries) ListEdgesTo(ctx context.Context, toID string) ([]Edge, error) {
	rows, err := q.query(ctx, q.listEdgesToStmt, listEdgesTo, toID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Edge{}
	for rows.Next() {
		var i Edge
		if err := rows.Scan(
			&i.ID,
			&i.FactID,
			&i.FromID,
			&i.ToID,
			&i.Kind,
			&i.Path,
			&i.Line,
			&i.ColumnNo,
			&i.EndLine,
			&i.Properties,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listExternalEdgesMatching = `-- name: ListExternalEdgesMatching :many
SELECT edges.id, edges.fact_id, edges.from_id, edges.to_id, edges.kind, edges.path, edges.line, edges.column_no, edges.end_line, edges.properties
FROM edges
JOIN nodes ON nodes.id = edges.to_id
WHERE nodes.external = 1
  AND (
      nodes.qualified_name = ?1
      OR nodes.qualified_name = ?2
      OR nodes.name = ?1
      OR nodes.name = ?2
  )
ORDER BY edges.kind, edges.from_id, edges.id
`

type ListExternalEdgesMatchingParams struct {
	QualifiedName string `json:"qualified_name"`
	Name          string `json:"name"`
}

func (q *Queries) ListExternalEdgesMatching(ctx context.Context, arg ListExternalEdgesMatchingParams) ([]Edge, error) {
	rows, err := q.query(ctx, q.listExternalEdgesMatchingStmt, listExternalEdgesMatching, arg.QualifiedName, arg.Name)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Edge{}
	for rows.Next() {
		var i Edge
		if err := rows.Scan(
			&i.ID,
			&i.FactID,
			&i.FromID,
			&i.ToID,
			&i.Kind,
			&i.Path,
			&i.Line,
			&i.ColumnNo,
			&i.EndLine,
			&i.Properties,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
