// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: edges.sql

package sqlcgen

import (
	"context"
)

const countEdges = `-- name: CountEdges :one
SELECT COUNT(*) FROM edges
`

func (q *Queries) CountEdges(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countEdges)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countEdgesByKind = `-- name: CountEdgesByKind :many
SELECT kind, COUNT(*) AS count FROM edges GROUP BY kind ORDER BY kind
`

type CountEdgesByKindRow struct {
	Kind  string `json:"kind"`
	Count int64  `json:"count"`
}

func (q *Queries) CountEdgesByKind(ctx context.Context) ([]CountEdgesByKindRow, error) {
	rows, err := q.db.QueryContext(ctx, countEdgesByKind)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CountEdgesByKindRow{}
	for rows.Next() {
		var i CountEdgesByKindRow
		if err := rows.Scan(&i.Kind, &i.Count); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const deleteAllEdges = `-- name: DeleteAllEdges :exec
DELETE FROM edges
`

func (q *Queries) DeleteAllEdges(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, deleteAllEdges)
	return err
}

const deleteEdgesByFact = `-- name: DeleteEdgesByFact :exec
DELETE FROM edges WHERE fact_id = ?
`

func (q *Queries) DeleteEdgesByFact(ctx context.Context, factID string) error {
	_, err := q.db.ExecContext(ctx, deleteEdgesByFact, factID)
	return err
}

const deleteEdgesByOwnerFacts = `-- name: DeleteEdgesByOwnerFacts :exec
DELETE FROM edges WHERE fact_id IN (SELECT id FROM facts WHERE owner_file = ?)
`

func (q *Queries) DeleteEdgesByOwnerFacts(ctx context.Context, ownerFile string) error {
	_, err := q.db.ExecContext(ctx, deleteEdgesByOwnerFacts, ownerFile)
	return err
}

const insertEdge = `-- name: InsertEdge :exec
INSERT INTO edges(
    id, fact_id, from_id, to_id, kind, path, line, column_no, end_line, properties
) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
`

type InsertEdgeParams struct {
	ID         string `json:"id"`
	FactID     string `json:"fact_id"`
	FromID     string `json:"from_id"`
	ToID       string `json:"to_id"`
	Kind       string `json:"kind"`
	Path       string `json:"path"`
	Line       int64  `json:"line"`
	ColumnNo   int64  `json:"column_no"`
	EndLine    int64  `json:"end_line"`
	Properties string `json:"properties"`
}

func (q *Queries) InsertEdge(ctx context.Context, arg InsertEdgeParams) error {
	_, err := q.db.ExecContext(ctx, insertEdge,
		arg.ID,
		arg.FactID,
		arg.FromID,
		arg.ToID,
		arg.Kind,
		arg.Path,
		arg.Line,
		arg.ColumnNo,
		arg.EndLine,
		arg.Properties,
	)
	return err
}

const listEdgesFrom = `-- name: ListEdgesFrom :many
SELECT id, fact_id, from_id, to_id, kind, path, line, column_no, end_line, properties FROM edges WHERE from_id = ? ORDER BY kind, to_id, id
`

func (q *Queries) ListEdgesFrom(ctx context.Context, fromID string) ([]Edge, error) {
	rows, err := q.db.QueryContext(ctx, listEdgesFrom, fromID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Edge{}
	for rows.Next() {
		var i Edge
		if err := rows.Scan(
			&i.ID,
			&i.FactID,
			&i.FromID,
			&i.ToID,
			&i.Kind,
			&i.Path,
			&i.Line,
			&i.ColumnNo,
			&i.EndLine,
			&i.Properties,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listEdgesTo = `-- name: ListEdgesTo :many
SELECT id, fact_id, from_id, to_id, kind, path, line, column_no, end_line, properties FROM edges WHERE to_id = ? ORDER BY kind, from_id, id
`

func (q *Queries) ListEdgesTo(ctx context.Context, toID string) ([]Edge, error) {
	rows, err := q.db.QueryContext(ctx, listEdgesTo, toID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Edge{}
	for rows.Next() {
		var i Edge
		if err := rows.Scan(
			&i.ID,
			&i.FactID,
			&i.FromID,
			&i.ToID,
			&i.Kind,
			&i.Path,
			&i.Line,
			&i.ColumnNo,
			&i.EndLine,
			&i.Properties,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
