// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: embeddings.sql

package sqlcgen

import (
	"context"
)

const deleteStaleEmbeddings = `-- name: DeleteStaleEmbeddings :execrows
DELETE FROM embeddings
WHERE model = ? AND node_id NOT IN (
    SELECT id FROM nodes
    WHERE external = 0
      AND kind IN ('function', 'method', 'type', 'class', 'interface', 'endpoint')
)
`

func (q *Queries) DeleteStaleEmbeddings(ctx context.Context, model string) (int64, error) {
	result, err := q.exec(ctx, q.deleteStaleEmbeddingsStmt, deleteStaleEmbeddings, model)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const listEmbeddingHashesByModel = `-- name: ListEmbeddingHashesByModel :many
SELECT node_id, content_hash FROM embeddings WHERE model = ? ORDER BY node_id
`

type ListEmbeddingHashesByModelRow struct {
	NodeID      string `json:"node_id"`
	ContentHash string `json:"content_hash"`
}

func (q *Queries) ListEmbeddingHashesByModel(ctx context.Context, model string) ([]ListEmbeddingHashesByModelRow, error) {
	rows, err := q.query(ctx, q.listEmbeddingHashesByModelStmt, listEmbeddingHashesByModel, model)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListEmbeddingHashesByModelRow{}
	for rows.Next() {
		var i ListEmbeddingHashesByModelRow
		if err := rows.Scan(&i.NodeID, &i.ContentHash); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listEmbeddingsByModel = `-- name: ListEmbeddingsByModel :many
SELECT node_id, model, content_hash, dimensions, vector_json, updated_at FROM embeddings WHERE model = ? ORDER BY node_id
`

func (q *Queries) ListEmbeddingsByModel(ctx context.Context, model string) ([]Embedding, error) {
	rows, err := q.query(ctx, q.listEmbeddingsByModelStmt, listEmbeddingsByModel, model)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Embedding{}
	for rows.Next() {
		var i Embedding
		if err := rows.Scan(
			&i.NodeID,
			&i.Model,
			&i.ContentHash,
			&i.Dimensions,
			&i.VectorJson,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSemanticCandidateNodes = `-- name: ListSemanticCandidateNodes :many
SELECT id, kind, name, qualified_name, language, path, line, column_no, end_line, properties, owner_file, external FROM nodes
WHERE external = 0
  AND kind IN ('function', 'method', 'type', 'class', 'interface', 'endpoint')
ORDER BY qualified_name, id
`

func (q *Queries) ListSemanticCandidateNodes(ctx context.Context) ([]Node, error) {
	rows, err := q.query(ctx, q.listSemanticCandidateNodesStmt, listSemanticCandidateNodes)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Node{}
	for rows.Next() {
		var i Node
		if err := rows.Scan(
			&i.ID,
			&i.Kind,
			&i.Name,
			&i.QualifiedName,
			&i.Language,
			&i.Path,
			&i.Line,
			&i.ColumnNo,
			&i.EndLine,
			&i.Properties,
			&i.OwnerFile,
			&i.External,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertEmbedding = `-- name: UpsertEmbedding :exec
INSERT INTO embeddings(node_id, model, content_hash, dimensions, vector_json, updated_at)
VALUES (?, ?, ?, ?, ?, ?)
ON CONFLICT(node_id, model) DO UPDATE SET
    content_hash = excluded.content_hash,
    dimensions = excluded.dimensions,
    vector_json = excluded.vector_json,
    updated_at = excluded.updated_at
`

type UpsertEmbeddingParams struct {
	NodeID      string `json:"node_id"`
	Model       string `json:"model"`
	ContentHash string `json:"content_hash"`
	Dimensions  int64  `json:"dimensions"`
	VectorJson  string `json:"vector_json"`
	UpdatedAt   string `json:"updated_at"`
}

func (q *Queries) UpsertEmbedding(ctx context.Context, arg UpsertEmbeddingParams) error {
	_, err := q.exec(ctx, q.upsertEmbeddingStmt, upsertEmbedding,
		arg.NodeID,
		arg.Model,
		arg.ContentHash,
		arg.Dimensions,
		arg.VectorJson,
		arg.UpdatedAt,
	)
	return err
}
