// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: facts.sql

package sqlcgen

import (
	"context"
)

const deleteFactsByOwner = `-- name: DeleteFactsByOwner :exec
DELETE FROM facts WHERE owner_file = ?
`

func (q *Queries) DeleteFactsByOwner(ctx context.Context, ownerFile string) error {
	_, err := q.db.ExecContext(ctx, deleteFactsByOwner, ownerFile)
	return err
}

const listDirtyFacts = `-- name: ListDirtyFacts :many
SELECT DISTINCT facts.id, facts.from_id, facts.kind, facts.target_id, facts.target, facts.target_kind, facts.path, facts.line, facts.column_no, facts.end_line, facts.properties, facts.owner_file
FROM facts
WHERE owner_file IN (SELECT owner_file FROM dirty_owners)
   OR target_id IN (SELECT node_id FROM dirty_nodes)
   OR target IN (SELECT target FROM dirty_targets)
ORDER BY owner_file, id
`

func (q *Queries) ListDirtyFacts(ctx context.Context) ([]Fact, error) {
	rows, err := q.db.QueryContext(ctx, listDirtyFacts)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Fact{}
	for rows.Next() {
		var i Fact
		if err := rows.Scan(
			&i.ID,
			&i.FromID,
			&i.Kind,
			&i.TargetID,
			&i.Target,
			&i.TargetKind,
			&i.Path,
			&i.Line,
			&i.ColumnNo,
			&i.EndLine,
			&i.Properties,
			&i.OwnerFile,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listFacts = `-- name: ListFacts :many
SELECT id, from_id, kind, target_id, target, target_kind, path, line, column_no, end_line, properties, owner_file FROM facts ORDER BY owner_file, id
`

func (q *Queries) ListFacts(ctx context.Context) ([]Fact, error) {
	rows, err := q.db.QueryContext(ctx, listFacts)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Fact{}
	for rows.Next() {
		var i Fact
		if err := rows.Scan(
			&i.ID,
			&i.FromID,
			&i.Kind,
			&i.TargetID,
			&i.Target,
			&i.TargetKind,
			&i.Path,
			&i.Line,
			&i.ColumnNo,
			&i.EndLine,
			&i.Properties,
			&i.OwnerFile,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertFact = `-- name: UpsertFact :exec
INSERT INTO facts(
    id, from_id, kind, target_id, target, target_kind, path, line, column_no,
    end_line, properties, owner_file
) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
ON CONFLICT(id) DO UPDATE SET
    from_id = excluded.from_id,
    kind = excluded.kind,
    target_id = excluded.target_id,
    target = excluded.target,
    target_kind = excluded.target_kind,
    path = excluded.path,
    line = excluded.line,
    column_no = excluded.column_no,
    end_line = excluded.end_line,
    properties = excluded.properties,
    owner_file = excluded.owner_file
`

type UpsertFactParams struct {
	ID         string `json:"id"`
	FromID     string `json:"from_id"`
	Kind       string `json:"kind"`
	TargetID   string `json:"target_id"`
	Target     string `json:"target"`
	TargetKind string `json:"target_kind"`
	Path       string `json:"path"`
	Line       int64  `json:"line"`
	ColumnNo   int64  `json:"column_no"`
	EndLine    int64  `json:"end_line"`
	Properties string `json:"properties"`
	OwnerFile  string `json:"owner_file"`
}

func (q *Queries) UpsertFact(ctx context.Context, arg UpsertFactParams) error {
	_, err := q.db.ExecContext(ctx, upsertFact,
		arg.ID,
		arg.FromID,
		arg.Kind,
		arg.TargetID,
		arg.Target,
		arg.TargetKind,
		arg.Path,
		arg.Line,
		arg.ColumnNo,
		arg.EndLine,
		arg.Properties,
		arg.OwnerFile,
	)
	return err
}
