// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: facts.sql

package sqlcgen

import (
	"context"
)

const countFacts = `-- name: CountFacts :one
SELECT COUNT(*) FROM facts
`

func (q *Queries) CountFacts(ctx context.Context) (int64, error) {
	row := q.queryRow(ctx, q.countFactsStmt, countFacts)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const deleteFactsByOwner = `-- name: DeleteFactsByOwner :exec
DELETE FROM facts WHERE owner_file = ?
`

func (q *Queries) DeleteFactsByOwner(ctx context.Context, ownerFile string) error {
	_, err := q.exec(ctx, q.deleteFactsByOwnerStmt, deleteFactsByOwner, ownerFile)
	return err
}

const listDirtyFactBatch = `-- name: ListDirtyFactBatch :many
SELECT facts.id, facts.from_id, facts.kind, facts.target_id, facts.target, facts.target_kind, facts.path, facts.line, facts.column_no, facts.end_line, facts.properties, facts.owner_file, CASE WHEN facts.target_id = '' OR target_node.id IS NOT NULL THEN 1 ELSE 0 END AS target_exists
FROM dirty_facts INDEXED BY dirty_facts_order
CROSS JOIN facts
LEFT JOIN nodes AS target_node ON target_node.id = facts.target_id
WHERE facts.id = dirty_facts.fact_id
ORDER BY dirty_facts.owner_file, dirty_facts.fact_id
LIMIT ?
`

type ListDirtyFactBatchRow struct {
	ID           string `json:"id"`
	FromID       string `json:"from_id"`
	Kind         string `json:"kind"`
	TargetID     string `json:"target_id"`
	Target       string `json:"target"`
	TargetKind   string `json:"target_kind"`
	Path         string `json:"path"`
	Line         int64  `json:"line"`
	ColumnNo     int64  `json:"column_no"`
	EndLine      int64  `json:"end_line"`
	Properties   string `json:"properties"`
	OwnerFile    string `json:"owner_file"`
	TargetExists int64  `json:"target_exists"`
}

func (q *Queries) ListDirtyFactBatch(ctx context.Context, limit int64) ([]ListDirtyFactBatchRow, error) {
	rows, err := q.query(ctx, q.listDirtyFactBatchStmt, listDirtyFactBatch, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListDirtyFactBatchRow{}
	for rows.Next() {
		var i ListDirtyFactBatchRow
		if err := rows.Scan(
			&i.ID,
			&i.FromID,
			&i.Kind,
			&i.TargetID,
			&i.Target,
			&i.TargetKind,
			&i.Path,
			&i.Line,
			&i.ColumnNo,
			&i.EndLine,
			&i.Properties,
			&i.OwnerFile,
			&i.TargetExists,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertFact = `-- name: UpsertFact :exec
INSERT INTO facts(
    id, from_id, kind, target_id, target, target_kind, path, line, column_no,
    end_line, properties, owner_file
) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
ON CONFLICT(id) DO UPDATE SET
    from_id = excluded.from_id,
    kind = excluded.kind,
    target_id = excluded.target_id,
    target = excluded.target,
    target_kind = excluded.target_kind,
    path = excluded.path,
    line = excluded.line,
    column_no = excluded.column_no,
    end_line = excluded.end_line,
    properties = excluded.properties,
    owner_file = excluded.owner_file
`

type UpsertFactParams struct {
	ID         string `json:"id"`
	FromID     string `json:"from_id"`
	Kind       string `json:"kind"`
	TargetID   string `json:"target_id"`
	Target     string `json:"target"`
	TargetKind string `json:"target_kind"`
	Path       string `json:"path"`
	Line       int64  `json:"line"`
	ColumnNo   int64  `json:"column_no"`
	EndLine    int64  `json:"end_line"`
	Properties string `json:"properties"`
	OwnerFile  string `json:"owner_file"`
}

func (q *Queries) UpsertFact(ctx context.Context, arg UpsertFactParams) error {
	_, err := q.exec(ctx, q.upsertFactStmt, upsertFact,
		arg.ID,
		arg.FromID,
		arg.Kind,
		arg.TargetID,
		arg.Target,
		arg.TargetKind,
		arg.Path,
		arg.Line,
		arg.ColumnNo,
		arg.EndLine,
		arg.Properties,
		arg.OwnerFile,
	)
	return err
}
