// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: facts.sql

package sqlcgen

import (
	"context"

	"github.com/cafecito-games/grafo/internal/storage/sqlite/identity"
)

const countFacts = `-- name: CountFacts :one
SELECT COUNT(*) FROM facts
`

func (q *Queries) CountFacts(ctx context.Context) (int64, error) {
	row := q.queryRow(ctx, q.countFactsStmt, countFacts)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const deleteFactsByOwner = `-- name: DeleteFactsByOwner :exec
DELETE FROM facts WHERE owner_path_id = (SELECT id FROM paths WHERE path = ?)
`

func (q *Queries) DeleteFactsByOwner(ctx context.Context, path string) error {
	_, err := q.exec(ctx, q.deleteFactsByOwnerStmt, deleteFactsByOwner, path)
	return err
}

const listDirtyFactBatch = `-- name: ListDirtyFactBatch :many
SELECT facts.id, facts.from_id, facts.source, facts.source_kind, facts.kind, facts.producer,
       facts.target_id, facts.target, facts.target_kind,
       COALESCE(location_paths.path, '') AS path, facts.line,
       facts.column_no, facts.end_line, facts.properties,
       COALESCE(owner_paths.path, '') AS owner_file,
       CASE WHEN location_paths.id IS NULL OR owner_paths.id IS NULL THEN 0 ELSE 1 END AS paths_resolved,
       CASE WHEN facts.from_id = '' OR source_node.id IS NOT NULL THEN 1 ELSE 0 END AS source_exists,
       CASE WHEN facts.target_id = '' OR target_node.id IS NOT NULL THEN 1 ELSE 0 END AS target_exists
FROM dirty_facts INDEXED BY dirty_facts_order
CROSS JOIN facts
LEFT JOIN paths AS location_paths ON location_paths.id = facts.path_id
LEFT JOIN paths AS owner_paths ON owner_paths.id = facts.owner_path_id
LEFT JOIN nodes AS source_node ON source_node.id = facts.from_id AND source_node.external = 0
LEFT JOIN nodes AS target_node ON target_node.id = facts.target_id
WHERE facts.id = dirty_facts.fact_id
ORDER BY dirty_facts.owner_file, dirty_facts.fact_id
LIMIT ?
`

type ListDirtyFactBatchRow struct {
	ID            identity.Key `json:"id"`
	FromID        identity.Key `json:"from_id"`
	Source        string       `json:"source"`
	SourceKind    string       `json:"source_kind"`
	Kind          string       `json:"kind"`
	Producer      string       `json:"producer"`
	TargetID      identity.Key `json:"target_id"`
	Target        string       `json:"target"`
	TargetKind    string       `json:"target_kind"`
	Path          string       `json:"path"`
	Line          int64        `json:"line"`
	ColumnNo      int64        `json:"column_no"`
	EndLine       int64        `json:"end_line"`
	Properties    string       `json:"properties"`
	OwnerFile     string       `json:"owner_file"`
	PathsResolved int64        `json:"paths_resolved"`
	SourceExists  int64        `json:"source_exists"`
	TargetExists  int64        `json:"target_exists"`
}

func (q *Queries) ListDirtyFactBatch(ctx context.Context, limit int64) ([]ListDirtyFactBatchRow, error) {
	rows, err := q.query(ctx, q.listDirtyFactBatchStmt, listDirtyFactBatch, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListDirtyFactBatchRow{}
	for rows.Next() {
		var i ListDirtyFactBatchRow
		if err := rows.Scan(
			&i.ID,
			&i.FromID,
			&i.Source,
			&i.SourceKind,
			&i.Kind,
			&i.Producer,
			&i.TargetID,
			&i.Target,
			&i.TargetKind,
			&i.Path,
			&i.Line,
			&i.ColumnNo,
			&i.EndLine,
			&i.Properties,
			&i.OwnerFile,
			&i.PathsResolved,
			&i.SourceExists,
			&i.TargetExists,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertFact = `-- name: UpsertFact :exec
INSERT INTO facts(
    id, from_id, source, source_kind, kind, producer, target_id, target, target_kind,
    path_id, line, column_no, end_line, properties, owner_path_id
) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
ON CONFLICT(id) DO UPDATE SET
    from_id = excluded.from_id,
    source = excluded.source,
    source_kind = excluded.source_kind,
    kind = excluded.kind,
    producer = excluded.producer,
    target_id = excluded.target_id,
    target = excluded.target,
    target_kind = excluded.target_kind,
    path_id = excluded.path_id,
    line = excluded.line,
    column_no = excluded.column_no,
    end_line = excluded.end_line,
    properties = excluded.properties,
    owner_path_id = excluded.owner_path_id
`

type UpsertFactParams struct {
	ID          identity.Key `json:"id"`
	FromID      identity.Key `json:"from_id"`
	Source      string       `json:"source"`
	SourceKind  string       `json:"source_kind"`
	Kind        string       `json:"kind"`
	Producer    string       `json:"producer"`
	TargetID    identity.Key `json:"target_id"`
	Target      string       `json:"target"`
	TargetKind  string       `json:"target_kind"`
	PathID      int64        `json:"path_id"`
	Line        int64        `json:"line"`
	ColumnNo    int64        `json:"column_no"`
	EndLine     int64        `json:"end_line"`
	Properties  string       `json:"properties"`
	OwnerPathID int64        `json:"owner_path_id"`
}

func (q *Queries) UpsertFact(ctx context.Context, arg UpsertFactParams) error {
	_, err := q.exec(ctx, q.upsertFactStmt, upsertFact,
		arg.ID,
		arg.FromID,
		arg.Source,
		arg.SourceKind,
		arg.Kind,
		arg.Producer,
		arg.TargetID,
		arg.Target,
		arg.TargetKind,
		arg.PathID,
		arg.Line,
		arg.ColumnNo,
		arg.EndLine,
		arg.Properties,
		arg.OwnerPathID,
	)
	return err
}
