// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: files.sql

package sqlcgen

import (
	"context"
)

const countFiles = `-- name: CountFiles :one
SELECT COUNT(*) FROM files
`

func (q *Queries) CountFiles(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countFiles)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const deleteFile = `-- name: DeleteFile :exec
DELETE FROM files WHERE path = ?
`

func (q *Queries) DeleteFile(ctx context.Context, path string) error {
	_, err := q.db.ExecContext(ctx, deleteFile, path)
	return err
}

const listFiles = `-- name: ListFiles :many
SELECT path, hash, language, size, modified_ns, indexed_at FROM files ORDER BY path
`

func (q *Queries) ListFiles(ctx context.Context) ([]File, error) {
	rows, err := q.db.QueryContext(ctx, listFiles)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []File{}
	for rows.Next() {
		var i File
		if err := rows.Scan(
			&i.Path,
			&i.Hash,
			&i.Language,
			&i.Size,
			&i.ModifiedNs,
			&i.IndexedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertFile = `-- name: UpsertFile :exec
INSERT INTO files(path, hash, language, size, modified_ns, indexed_at)
VALUES (?, ?, ?, ?, ?, ?)
ON CONFLICT(path) DO UPDATE SET
    hash = excluded.hash,
    language = excluded.language,
    size = excluded.size,
    modified_ns = excluded.modified_ns,
    indexed_at = excluded.indexed_at
`

type UpsertFileParams struct {
	Path       string `json:"path"`
	Hash       string `json:"hash"`
	Language   string `json:"language"`
	Size       int64  `json:"size"`
	ModifiedNs int64  `json:"modified_ns"`
	IndexedAt  string `json:"indexed_at"`
}

func (q *Queries) UpsertFile(ctx context.Context, arg UpsertFileParams) error {
	_, err := q.db.ExecContext(ctx, upsertFile,
		arg.Path,
		arg.Hash,
		arg.Language,
		arg.Size,
		arg.ModifiedNs,
		arg.IndexedAt,
	)
	return err
}
