// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlcgen

type DirtyFact struct {
	FactID    string `json:"fact_id"`
	OwnerFile string `json:"owner_file"`
}

type DirtyNode struct {
	NodeID string `json:"node_id"`
}

type DirtyOwner struct {
	OwnerFile string `json:"owner_file"`
}

type DirtyTarget struct {
	Target     string `json:"target"`
	TargetKind string `json:"target_kind"`
}

type Edge struct {
	ID         string `json:"id"`
	FactID     string `json:"fact_id"`
	FromID     string `json:"from_id"`
	ToID       string `json:"to_id"`
	Kind       string `json:"kind"`
	Path       string `json:"path"`
	Line       int64  `json:"line"`
	ColumnNo   int64  `json:"column_no"`
	EndLine    int64  `json:"end_line"`
	Properties string `json:"properties"`
	Producer   string `json:"producer"`
}

type Fact struct {
	ID         string `json:"id"`
	FromID     string `json:"from_id"`
	Kind       string `json:"kind"`
	TargetID   string `json:"target_id"`
	Target     string `json:"target"`
	TargetKind string `json:"target_kind"`
	Path       string `json:"path"`
	Line       int64  `json:"line"`
	ColumnNo   int64  `json:"column_no"`
	EndLine    int64  `json:"end_line"`
	Properties string `json:"properties"`
	OwnerFile  string `json:"owner_file"`
	Source     string `json:"source"`
	SourceKind string `json:"source_kind"`
	Producer   string `json:"producer"`
}

type File struct {
	Path       string `json:"path"`
	Hash       string `json:"hash"`
	Language   string `json:"language"`
	Size       int64  `json:"size"`
	ModifiedNs int64  `json:"modified_ns"`
	IndexedAt  string `json:"indexed_at"`
}

type Meta struct {
	Key   string `json:"key"`
	Value string `json:"value"`
}

type Node struct {
	ID                  string `json:"id"`
	Kind                string `json:"kind"`
	Name                string `json:"name"`
	QualifiedName       string `json:"qualified_name"`
	Language            string `json:"language"`
	Path                string `json:"path"`
	Line                int64  `json:"line"`
	ColumnNo            int64  `json:"column_no"`
	EndLine             int64  `json:"end_line"`
	Properties          string `json:"properties"`
	OwnerFile           string `json:"owner_file"`
	External            int64  `json:"external"`
	NameFolded          string `json:"name_folded"`
	QualifiedNameFolded string `json:"qualified_name_folded"`
}

type ReconciliationCleanup struct {
	ID int64 `json:"id"`
}
