// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: nodes.sql

package sqlcgen

import (
	"context"
)

const countExternalNodes = `-- name: CountExternalNodes :one
SELECT COUNT(*) FROM nodes WHERE external = 1
`

func (q *Queries) CountExternalNodes(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countExternalNodes)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countNodes = `-- name: CountNodes :one
SELECT COUNT(*) FROM nodes
`

func (q *Queries) CountNodes(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countNodes)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countNodesByKind = `-- name: CountNodesByKind :many
SELECT kind, COUNT(*) AS count FROM nodes GROUP BY kind ORDER BY kind
`

type CountNodesByKindRow struct {
	Kind  string `json:"kind"`
	Count int64  `json:"count"`
}

func (q *Queries) CountNodesByKind(ctx context.Context) ([]CountNodesByKindRow, error) {
	rows, err := q.db.QueryContext(ctx, countNodesByKind)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CountNodesByKindRow{}
	for rows.Next() {
		var i CountNodesByKindRow
		if err := rows.Scan(&i.Kind, &i.Count); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const deleteExternalNodes = `-- name: DeleteExternalNodes :exec
DELETE FROM nodes WHERE owner_file = '__external__'
`

func (q *Queries) DeleteExternalNodes(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, deleteExternalNodes)
	return err
}

const deleteNodesByOwner = `-- name: DeleteNodesByOwner :exec
DELETE FROM nodes WHERE owner_file = ?
`

func (q *Queries) DeleteNodesByOwner(ctx context.Context, ownerFile string) error {
	_, err := q.db.ExecContext(ctx, deleteNodesByOwner, ownerFile)
	return err
}

const deleteOrphanExternalNodes = `-- name: DeleteOrphanExternalNodes :exec
DELETE FROM nodes
WHERE external = 1
  AND NOT EXISTS (SELECT 1 FROM edges WHERE edges.to_id = nodes.id OR edges.from_id = nodes.id)
`

func (q *Queries) DeleteOrphanExternalNodes(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, deleteOrphanExternalNodes)
	return err
}

const findNodesByName = `-- name: FindNodesByName :many
SELECT id, kind, name, qualified_name, language, path, line, column_no, end_line, properties, owner_file, external FROM nodes
WHERE external = 0 AND name = ?
ORDER BY qualified_name, id
`

func (q *Queries) FindNodesByName(ctx context.Context, name string) ([]Node, error) {
	rows, err := q.db.QueryContext(ctx, findNodesByName, name)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Node{}
	for rows.Next() {
		var i Node
		if err := rows.Scan(
			&i.ID,
			&i.Kind,
			&i.Name,
			&i.QualifiedName,
			&i.Language,
			&i.Path,
			&i.Line,
			&i.ColumnNo,
			&i.EndLine,
			&i.Properties,
			&i.OwnerFile,
			&i.External,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const findNodesByNameKind = `-- name: FindNodesByNameKind :many
SELECT id, kind, name, qualified_name, language, path, line, column_no, end_line, properties, owner_file, external FROM nodes
WHERE external = 0 AND name = ? AND kind = ?
ORDER BY qualified_name, id
`

type FindNodesByNameKindParams struct {
	Name string `json:"name"`
	Kind string `json:"kind"`
}

func (q *Queries) FindNodesByNameKind(ctx context.Context, arg FindNodesByNameKindParams) ([]Node, error) {
	rows, err := q.db.QueryContext(ctx, findNodesByNameKind, arg.Name, arg.Kind)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Node{}
	for rows.Next() {
		var i Node
		if err := rows.Scan(
			&i.ID,
			&i.Kind,
			&i.Name,
			&i.QualifiedName,
			&i.Language,
			&i.Path,
			&i.Line,
			&i.ColumnNo,
			&i.EndLine,
			&i.Properties,
			&i.OwnerFile,
			&i.External,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const findNodesExact = `-- name: FindNodesExact :many
SELECT id, kind, name, qualified_name, language, path, line, column_no, end_line, properties, owner_file, external FROM nodes
WHERE external = 0 AND (qualified_name = ? OR name = ?)
ORDER BY qualified_name, id
`

type FindNodesExactParams struct {
	QualifiedName string `json:"qualified_name"`
	Name          string `json:"name"`
}

func (q *Queries) FindNodesExact(ctx context.Context, arg FindNodesExactParams) ([]Node, error) {
	rows, err := q.db.QueryContext(ctx, findNodesExact, arg.QualifiedName, arg.Name)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Node{}
	for rows.Next() {
		var i Node
		if err := rows.Scan(
			&i.ID,
			&i.Kind,
			&i.Name,
			&i.QualifiedName,
			&i.Language,
			&i.Path,
			&i.Line,
			&i.ColumnNo,
			&i.EndLine,
			&i.Properties,
			&i.OwnerFile,
			&i.External,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const findNodesExactKind = `-- name: FindNodesExactKind :many
SELECT id, kind, name, qualified_name, language, path, line, column_no, end_line, properties, owner_file, external FROM nodes
WHERE external = 0
  AND (qualified_name = ? OR name = ?)
  AND kind = ?
ORDER BY qualified_name, id
`

type FindNodesExactKindParams struct {
	QualifiedName string `json:"qualified_name"`
	Name          string `json:"name"`
	Kind          string `json:"kind"`
}

func (q *Queries) FindNodesExactKind(ctx context.Context, arg FindNodesExactKindParams) ([]Node, error) {
	rows, err := q.db.QueryContext(ctx, findNodesExactKind, arg.QualifiedName, arg.Name, arg.Kind)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Node{}
	for rows.Next() {
		var i Node
		if err := rows.Scan(
			&i.ID,
			&i.Kind,
			&i.Name,
			&i.QualifiedName,
			&i.Language,
			&i.Path,
			&i.Line,
			&i.ColumnNo,
			&i.EndLine,
			&i.Properties,
			&i.OwnerFile,
			&i.External,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getNode = `-- name: GetNode :one
SELECT id, kind, name, qualified_name, language, path, line, column_no, end_line, properties, owner_file, external FROM nodes WHERE id = ?
`

func (q *Queries) GetNode(ctx context.Context, id string) (Node, error) {
	row := q.db.QueryRowContext(ctx, getNode, id)
	var i Node
	err := row.Scan(
		&i.ID,
		&i.Kind,
		&i.Name,
		&i.QualifiedName,
		&i.Language,
		&i.Path,
		&i.Line,
		&i.ColumnNo,
		&i.EndLine,
		&i.Properties,
		&i.OwnerFile,
		&i.External,
	)
	return i, err
}

const searchNodes = `-- name: SearchNodes :many
SELECT id, kind, name, qualified_name, language, path, line, column_no, end_line, properties, owner_file, external FROM nodes
WHERE lower(name) LIKE '%' || lower(?1) || '%'
   OR lower(qualified_name) LIKE '%' || lower(?1) || '%'
ORDER BY
    external, length(qualified_name), qualified_name, id
LIMIT ?2
`

type SearchNodesParams struct {
	Term       string `json:"term"`
	MaxResults int64  `json:"max_results"`
}

func (q *Queries) SearchNodes(ctx context.Context, arg SearchNodesParams) ([]Node, error) {
	rows, err := q.db.QueryContext(ctx, searchNodes, arg.Term, arg.MaxResults)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Node{}
	for rows.Next() {
		var i Node
		if err := rows.Scan(
			&i.ID,
			&i.Kind,
			&i.Name,
			&i.QualifiedName,
			&i.Language,
			&i.Path,
			&i.Line,
			&i.ColumnNo,
			&i.EndLine,
			&i.Properties,
			&i.OwnerFile,
			&i.External,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertNode = `-- name: UpsertNode :exec
INSERT INTO nodes(
    id, kind, name, qualified_name, language, path, line, column_no, end_line,
    properties, owner_file, external
) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
ON CONFLICT(id) DO UPDATE SET
    kind = excluded.kind,
    name = excluded.name,
    qualified_name = excluded.qualified_name,
    language = excluded.language,
    path = excluded.path,
    line = excluded.line,
    column_no = excluded.column_no,
    end_line = excluded.end_line,
    properties = excluded.properties,
    owner_file = excluded.owner_file,
    external = excluded.external
`

type UpsertNodeParams struct {
	ID            string `json:"id"`
	Kind          string `json:"kind"`
	Name          string `json:"name"`
	QualifiedName string `json:"qualified_name"`
	Language      string `json:"language"`
	Path          string `json:"path"`
	Line          int64  `json:"line"`
	ColumnNo      int64  `json:"column_no"`
	EndLine       int64  `json:"end_line"`
	Properties    string `json:"properties"`
	OwnerFile     string `json:"owner_file"`
	External      int64  `json:"external"`
}

func (q *Queries) UpsertNode(ctx context.Context, arg UpsertNodeParams) error {
	_, err := q.db.ExecContext(ctx, upsertNode,
		arg.ID,
		arg.Kind,
		arg.Name,
		arg.QualifiedName,
		arg.Language,
		arg.Path,
		arg.Line,
		arg.ColumnNo,
		arg.EndLine,
		arg.Properties,
		arg.OwnerFile,
		arg.External,
	)
	return err
}
