// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: nodes.sql

package sqlcgen

import (
	"context"
)

const countExternalNodes = `-- name: CountExternalNodes :one
SELECT COUNT(*) FROM nodes WHERE external = 1
`

func (q *Queries) CountExternalNodes(ctx context.Context) (int64, error) {
	row := q.queryRow(ctx, q.countExternalNodesStmt, countExternalNodes)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countNodeMatchesByName = `-- name: CountNodeMatchesByName :one
SELECT
    COUNT(*) AS total,
    CAST(COALESCE(SUM(CASE WHEN name = ?1 THEN 1 ELSE 0 END), 0) AS INTEGER) AS strict_matches
FROM nodes
WHERE name = ?1 COLLATE NOCASE
  AND external = CAST(?2 AS INTEGER)
  AND (CAST(?3 AS TEXT) = '' OR kind = CAST(?3 AS TEXT))
`

type CountNodeMatchesByNameParams struct {
	Target   string `json:"target"`
	External int64  `json:"external"`
	Kind     string `json:"kind"`
}

type CountNodeMatchesByNameRow struct {
	Total         int64 `json:"total"`
	StrictMatches int64 `json:"strict_matches"`
}

func (q *Queries) CountNodeMatchesByName(ctx context.Context, arg CountNodeMatchesByNameParams) (CountNodeMatchesByNameRow, error) {
	row := q.queryRow(ctx, q.countNodeMatchesByNameStmt, countNodeMatchesByName, arg.Target, arg.External, arg.Kind)
	var i CountNodeMatchesByNameRow
	err := row.Scan(&i.Total, &i.StrictMatches)
	return i, err
}

const countNodeMatchesByQualifiedName = `-- name: CountNodeMatchesByQualifiedName :one
SELECT
    COUNT(*) AS total,
    CAST(COALESCE(SUM(CASE WHEN qualified_name = ?1 THEN 1 ELSE 0 END), 0) AS INTEGER) AS strict_matches
FROM nodes
WHERE qualified_name = ?1 COLLATE NOCASE
  AND external = CAST(?2 AS INTEGER)
  AND (CAST(?3 AS TEXT) = '' OR kind = CAST(?3 AS TEXT))
`

type CountNodeMatchesByQualifiedNameParams struct {
	Target   string `json:"target"`
	External int64  `json:"external"`
	Kind     string `json:"kind"`
}

type CountNodeMatchesByQualifiedNameRow struct {
	Total         int64 `json:"total"`
	StrictMatches int64 `json:"strict_matches"`
}

func (q *Queries) CountNodeMatchesByQualifiedName(ctx context.Context, arg CountNodeMatchesByQualifiedNameParams) (CountNodeMatchesByQualifiedNameRow, error) {
	row := q.queryRow(ctx, q.countNodeMatchesByQualifiedNameStmt, countNodeMatchesByQualifiedName, arg.Target, arg.External, arg.Kind)
	var i CountNodeMatchesByQualifiedNameRow
	err := row.Scan(&i.Total, &i.StrictMatches)
	return i, err
}

const countNodeMatchesBySubstring = `-- name: CountNodeMatchesBySubstring :one
SELECT
    COUNT(*) AS total,
    CAST(COALESCE(SUM(CASE WHEN instr(qualified_name, ?1) > 0 OR instr(name, ?1) > 0 THEN 1 ELSE 0 END), 0) AS INTEGER) AS strict_matches
FROM nodes
WHERE (lower(name) LIKE '%' || lower(?1) || '%'
    OR lower(qualified_name) LIKE '%' || lower(?1) || '%')
  AND external = CAST(?2 AS INTEGER)
  AND (CAST(?3 AS TEXT) = '' OR kind = CAST(?3 AS TEXT))
`

type CountNodeMatchesBySubstringParams struct {
	Target   string `json:"target"`
	External int64  `json:"external"`
	Kind     string `json:"kind"`
}

type CountNodeMatchesBySubstringRow struct {
	Total         int64 `json:"total"`
	StrictMatches int64 `json:"strict_matches"`
}

func (q *Queries) CountNodeMatchesBySubstring(ctx context.Context, arg CountNodeMatchesBySubstringParams) (CountNodeMatchesBySubstringRow, error) {
	row := q.queryRow(ctx, q.countNodeMatchesBySubstringStmt, countNodeMatchesBySubstring, arg.Target, arg.External, arg.Kind)
	var i CountNodeMatchesBySubstringRow
	err := row.Scan(&i.Total, &i.StrictMatches)
	return i, err
}

const countNodes = `-- name: CountNodes :one
SELECT COUNT(*) FROM nodes
`

func (q *Queries) CountNodes(ctx context.Context) (int64, error) {
	row := q.queryRow(ctx, q.countNodesStmt, countNodes)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countNodesByKind = `-- name: CountNodesByKind :many
SELECT kind, COUNT(*) AS count FROM nodes GROUP BY kind ORDER BY kind
`

type CountNodesByKindRow struct {
	Kind  string `json:"kind"`
	Count int64  `json:"count"`
}

func (q *Queries) CountNodesByKind(ctx context.Context) ([]CountNodesByKindRow, error) {
	rows, err := q.query(ctx, q.countNodesByKindStmt, countNodesByKind)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CountNodesByKindRow{}
	for rows.Next() {
		var i CountNodesByKindRow
		if err := rows.Scan(&i.Kind, &i.Count); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const deleteExternalNodes = `-- name: DeleteExternalNodes :exec
DELETE FROM nodes WHERE owner_file = '__external__'
`

func (q *Queries) DeleteExternalNodes(ctx context.Context) error {
	_, err := q.exec(ctx, q.deleteExternalNodesStmt, deleteExternalNodes)
	return err
}

const deleteNodesByOwner = `-- name: DeleteNodesByOwner :exec
DELETE FROM nodes WHERE owner_file = ?
`

func (q *Queries) DeleteNodesByOwner(ctx context.Context, ownerFile string) error {
	_, err := q.exec(ctx, q.deleteNodesByOwnerStmt, deleteNodesByOwner, ownerFile)
	return err
}

const deleteOrphanExternalNodes = `-- name: DeleteOrphanExternalNodes :exec
DELETE FROM nodes
WHERE external = 1
  AND NOT EXISTS (SELECT 1 FROM edges WHERE edges.to_id = nodes.id OR edges.from_id = nodes.id)
`

func (q *Queries) DeleteOrphanExternalNodes(ctx context.Context) error {
	_, err := q.exec(ctx, q.deleteOrphanExternalNodesStmt, deleteOrphanExternalNodes)
	return err
}

const findNodesExact = `-- name: FindNodesExact :many
SELECT nodes.id, nodes.kind, nodes.qualified_name
FROM nodes INDEXED BY nodes_qualified_resolve
WHERE nodes.qualified_name = ?1 AND nodes.external = 0
UNION ALL
SELECT nodes.id, nodes.kind, nodes.qualified_name
FROM nodes INDEXED BY nodes_name_resolve
WHERE nodes.name = ?1 AND nodes.external = 0 AND nodes.qualified_name != ?1
`

type FindNodesExactRow struct {
	ID            string `json:"id"`
	Kind          string `json:"kind"`
	QualifiedName string `json:"qualified_name"`
}

func (q *Queries) FindNodesExact(ctx context.Context, target string) ([]FindNodesExactRow, error) {
	rows, err := q.query(ctx, q.findNodesExactStmt, findNodesExact, target)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []FindNodesExactRow{}
	for rows.Next() {
		var i FindNodesExactRow
		if err := rows.Scan(&i.ID, &i.Kind, &i.QualifiedName); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const findNodesExactKind = `-- name: FindNodesExactKind :many
SELECT nodes.id, nodes.kind, nodes.qualified_name
FROM nodes INDEXED BY nodes_qualified_resolve
WHERE nodes.qualified_name = ?1 AND nodes.external = 0 AND nodes.kind = ?2
UNION ALL
SELECT nodes.id, nodes.kind, nodes.qualified_name
FROM nodes INDEXED BY nodes_name_resolve
WHERE nodes.name = ?1 AND nodes.external = 0 AND nodes.kind = ?2 AND nodes.qualified_name != ?1
`

type FindNodesExactKindParams struct {
	Target string `json:"target"`
	Kind   string `json:"kind"`
}

type FindNodesExactKindRow struct {
	ID            string `json:"id"`
	Kind          string `json:"kind"`
	QualifiedName string `json:"qualified_name"`
}

func (q *Queries) FindNodesExactKind(ctx context.Context, arg FindNodesExactKindParams) ([]FindNodesExactKindRow, error) {
	rows, err := q.query(ctx, q.findNodesExactKindStmt, findNodesExactKind, arg.Target, arg.Kind)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []FindNodesExactKindRow{}
	for rows.Next() {
		var i FindNodesExactKindRow
		if err := rows.Scan(&i.ID, &i.Kind, &i.QualifiedName); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getNode = `-- name: GetNode :one
SELECT id, kind, name, qualified_name, language, path, line, column_no, end_line, properties, owner_file, external, name_folded, qualified_name_folded FROM nodes WHERE id = ?
`

func (q *Queries) GetNode(ctx context.Context, id string) (Node, error) {
	row := q.queryRow(ctx, q.getNodeStmt, getNode, id)
	var i Node
	err := row.Scan(
		&i.ID,
		&i.Kind,
		&i.Name,
		&i.QualifiedName,
		&i.Language,
		&i.Path,
		&i.Line,
		&i.ColumnNo,
		&i.EndLine,
		&i.Properties,
		&i.OwnerFile,
		&i.External,
		&i.NameFolded,
		&i.QualifiedNameFolded,
	)
	return i, err
}

const listCanonicalMessages = `-- name: ListCanonicalMessages :many
SELECT id, kind, name, qualified_name, language, path, line, column_no, end_line, properties, owner_file, external, name_folded, qualified_name_folded FROM nodes
WHERE kind = 'type'
  AND external = 0
  AND json_extract(properties, '$.declaration') = 'message'
  AND (
      CAST(?1 AS TEXT) = ''
      OR substr(qualified_name, 1, length(CAST(?1 AS TEXT)) + 1) = CAST(?1 AS TEXT) || '.'
  )
  AND (
      CAST(?2 AS TEXT) = ''
      OR name = CAST(?2 AS TEXT)
      OR qualified_name = CAST(?2 AS TEXT)
  )
ORDER BY qualified_name, id
LIMIT ?3
`

type ListCanonicalMessagesParams struct {
	PackageName string `json:"package_name"`
	MessageName string `json:"message_name"`
	MaxResults  int64  `json:"max_results"`
}

func (q *Queries) ListCanonicalMessages(ctx context.Context, arg ListCanonicalMessagesParams) ([]Node, error) {
	rows, err := q.query(ctx, q.listCanonicalMessagesStmt, listCanonicalMessages, arg.PackageName, arg.MessageName, arg.MaxResults)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Node{}
	for rows.Next() {
		var i Node
		if err := rows.Scan(
			&i.ID,
			&i.Kind,
			&i.Name,
			&i.QualifiedName,
			&i.Language,
			&i.Path,
			&i.Line,
			&i.ColumnNo,
			&i.EndLine,
			&i.Properties,
			&i.OwnerFile,
			&i.External,
			&i.NameFolded,
			&i.QualifiedNameFolded,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listExternalNodesMatching = `-- name: ListExternalNodesMatching :many
SELECT id, kind, name, qualified_name, language, path, line, column_no, end_line, properties, owner_file, external, name_folded, qualified_name_folded FROM nodes
WHERE external = 1
  AND (
      qualified_name = ?1
      OR qualified_name = ?2
      OR name = ?1
      OR name = ?2
  )
ORDER BY id
`

type ListExternalNodesMatchingParams struct {
	QualifiedName string `json:"qualified_name"`
	Name          string `json:"name"`
}

func (q *Queries) ListExternalNodesMatching(ctx context.Context, arg ListExternalNodesMatchingParams) ([]Node, error) {
	rows, err := q.query(ctx, q.listExternalNodesMatchingStmt, listExternalNodesMatching, arg.QualifiedName, arg.Name)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Node{}
	for rows.Next() {
		var i Node
		if err := rows.Scan(
			&i.ID,
			&i.Kind,
			&i.Name,
			&i.QualifiedName,
			&i.Language,
			&i.Path,
			&i.Line,
			&i.ColumnNo,
			&i.EndLine,
			&i.Properties,
			&i.OwnerFile,
			&i.External,
			&i.NameFolded,
			&i.QualifiedNameFolded,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listNodesByKind = `-- name: ListNodesByKind :many
SELECT id, kind, name, qualified_name, language, path, line, column_no, end_line, properties, owner_file, external, name_folded, qualified_name_folded FROM nodes
WHERE kind = ?1
  AND external >= ?2
  AND external <= ?3
  AND (instr(name_folded, ?4) > 0 OR instr(qualified_name_folded, ?4) > 0)
ORDER BY qualified_name, id
LIMIT ?5
`

type ListNodesByKindParams struct {
	Kind         string `json:"kind"`
	MinExternal  int64  `json:"min_external"`
	MaxExternal  int64  `json:"max_external"`
	NameFragment string `json:"name_fragment"`
	MaxResults   int64  `json:"max_results"`
}

func (q *Queries) ListNodesByKind(ctx context.Context, arg ListNodesByKindParams) ([]Node, error) {
	rows, err := q.query(ctx, q.listNodesByKindStmt, listNodesByKind,
		arg.Kind,
		arg.MinExternal,
		arg.MaxExternal,
		arg.NameFragment,
		arg.MaxResults,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Node{}
	for rows.Next() {
		var i Node
		if err := rows.Scan(
			&i.ID,
			&i.Kind,
			&i.Name,
			&i.QualifiedName,
			&i.Language,
			&i.Path,
			&i.Line,
			&i.ColumnNo,
			&i.EndLine,
			&i.Properties,
			&i.OwnerFile,
			&i.External,
			&i.NameFolded,
			&i.QualifiedNameFolded,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const matchNodesByName = `-- name: MatchNodesByName :many
SELECT id, kind, name, qualified_name, language, path, line, column_no, end_line,
       properties, owner_file, external, name_folded, qualified_name_folded
FROM (
    SELECT nodes.id, nodes.kind, nodes.name, nodes.qualified_name, nodes.language, nodes.path, nodes.line, nodes.column_no, nodes.end_line, nodes.properties, nodes.owner_file, nodes.external, nodes.name_folded, nodes.qualified_name_folded, CASE WHEN name = ?1 THEN 0 ELSE 1 END AS strict_rank
    FROM nodes
    WHERE name = ?1 COLLATE NOCASE
      AND external = CAST(?2 AS INTEGER)
      AND (CAST(?3 AS TEXT) = '' OR kind = CAST(?3 AS TEXT))
)
ORDER BY strict_rank, length(qualified_name), qualified_name, id
LIMIT ?4
`

type MatchNodesByNameParams struct {
	Target     string `json:"target"`
	External   int64  `json:"external"`
	Kind       string `json:"kind"`
	MaxResults int64  `json:"max_results"`
}

func (q *Queries) MatchNodesByName(ctx context.Context, arg MatchNodesByNameParams) ([]Node, error) {
	rows, err := q.query(ctx, q.matchNodesByNameStmt, matchNodesByName,
		arg.Target,
		arg.External,
		arg.Kind,
		arg.MaxResults,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Node{}
	for rows.Next() {
		var i Node
		if err := rows.Scan(
			&i.ID,
			&i.Kind,
			&i.Name,
			&i.QualifiedName,
			&i.Language,
			&i.Path,
			&i.Line,
			&i.ColumnNo,
			&i.EndLine,
			&i.Properties,
			&i.OwnerFile,
			&i.External,
			&i.NameFolded,
			&i.QualifiedNameFolded,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const matchNodesByQualifiedName = `-- name: MatchNodesByQualifiedName :many

SELECT id, kind, name, qualified_name, language, path, line, column_no, end_line,
       properties, owner_file, external, name_folded, qualified_name_folded
FROM (
    SELECT nodes.id, nodes.kind, nodes.name, nodes.qualified_name, nodes.language, nodes.path, nodes.line, nodes.column_no, nodes.end_line, nodes.properties, nodes.owner_file, nodes.external, nodes.name_folded, nodes.qualified_name_folded, CASE WHEN qualified_name = ?1 THEN 0 ELSE 1 END AS strict_rank
    FROM nodes
    WHERE qualified_name = ?1 COLLATE NOCASE
      AND external = CAST(?2 AS INTEGER)
      AND (CAST(?3 AS TEXT) = '' OR kind = CAST(?3 AS TEXT))
)
ORDER BY strict_rank, length(qualified_name), qualified_name, id
LIMIT ?4
`

type MatchNodesByQualifiedNameParams struct {
	Target     string `json:"target"`
	External   int64  `json:"external"`
	Kind       string `json:"kind"`
	MaxResults int64  `json:"max_results"`
}

// Selector resolution queries. Each level is narrow and index-backed so
// ambiguity is decided from complete counts instead of a truncated substring
// window. nodes_qualified and nodes_name are COLLATE NOCASE indexes, so the
// case-insensitive equality below stays an index seek; the case-sensitive
// ("strict") form is counted separately because it is stronger evidence.
// @external selects the scope rather than discarding one: the adapter asks for
// local declarations first and falls back to external boundary nodes, so exact
// evidence about an external target is still exact rather than being pushed down
// into the weaker substring level.
func (q *Queries) MatchNodesByQualifiedName(ctx context.Context, arg MatchNodesByQualifiedNameParams) ([]Node, error) {
	rows, err := q.query(ctx, q.matchNodesByQualifiedNameStmt, matchNodesByQualifiedName,
		arg.Target,
		arg.External,
		arg.Kind,
		arg.MaxResults,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Node{}
	for rows.Next() {
		var i Node
		if err := rows.Scan(
			&i.ID,
			&i.Kind,
			&i.Name,
			&i.QualifiedName,
			&i.Language,
			&i.Path,
			&i.Line,
			&i.ColumnNo,
			&i.EndLine,
			&i.Properties,
			&i.OwnerFile,
			&i.External,
			&i.NameFolded,
			&i.QualifiedNameFolded,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const matchNodesBySubstring = `-- name: MatchNodesBySubstring :many
SELECT id, kind, name, qualified_name, language, path, line, column_no, end_line,
       properties, owner_file, external, name_folded, qualified_name_folded
FROM (
    SELECT nodes.id, nodes.kind, nodes.name, nodes.qualified_name, nodes.language, nodes.path, nodes.line, nodes.column_no, nodes.end_line, nodes.properties, nodes.owner_file, nodes.external, nodes.name_folded, nodes.qualified_name_folded,
        CASE WHEN instr(qualified_name, ?1) > 0 OR instr(name, ?1) > 0 THEN 0 ELSE 1 END AS strict_rank
    FROM nodes
    WHERE (lower(name) LIKE '%' || lower(?1) || '%'
        OR lower(qualified_name) LIKE '%' || lower(?1) || '%')
      AND external = CAST(?2 AS INTEGER)
      AND (CAST(?3 AS TEXT) = '' OR kind = CAST(?3 AS TEXT))
)
ORDER BY strict_rank, length(qualified_name), qualified_name, id
LIMIT ?4
`

type MatchNodesBySubstringParams struct {
	Target     string `json:"target"`
	External   int64  `json:"external"`
	Kind       string `json:"kind"`
	MaxResults int64  `json:"max_results"`
}

func (q *Queries) MatchNodesBySubstring(ctx context.Context, arg MatchNodesBySubstringParams) ([]Node, error) {
	rows, err := q.query(ctx, q.matchNodesBySubstringStmt, matchNodesBySubstring,
		arg.Target,
		arg.External,
		arg.Kind,
		arg.MaxResults,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Node{}
	for rows.Next() {
		var i Node
		if err := rows.Scan(
			&i.ID,
			&i.Kind,
			&i.Name,
			&i.QualifiedName,
			&i.Language,
			&i.Path,
			&i.Line,
			&i.ColumnNo,
			&i.EndLine,
			&i.Properties,
			&i.OwnerFile,
			&i.External,
			&i.NameFolded,
			&i.QualifiedNameFolded,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchNodes = `-- name: SearchNodes :many
SELECT id, kind, name, qualified_name, language, path, line, column_no, end_line, properties, owner_file, external, name_folded, qualified_name_folded FROM nodes
WHERE name_folded LIKE '%' || CAST(?1 AS TEXT) || '%'
   OR qualified_name_folded LIKE '%' || CAST(?1 AS TEXT) || '%'
ORDER BY
    external, length(qualified_name), qualified_name, id
LIMIT ?2
`

type SearchNodesParams struct {
	Term       string `json:"term"`
	MaxResults int64  `json:"max_results"`
}

func (q *Queries) SearchNodes(ctx context.Context, arg SearchNodesParams) ([]Node, error) {
	rows, err := q.query(ctx, q.searchNodesStmt, searchNodes, arg.Term, arg.MaxResults)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Node{}
	for rows.Next() {
		var i Node
		if err := rows.Scan(
			&i.ID,
			&i.Kind,
			&i.Name,
			&i.QualifiedName,
			&i.Language,
			&i.Path,
			&i.Line,
			&i.ColumnNo,
			&i.EndLine,
			&i.Properties,
			&i.OwnerFile,
			&i.External,
			&i.NameFolded,
			&i.QualifiedNameFolded,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertNode = `-- name: UpsertNode :exec
INSERT INTO nodes(
    id, kind, name, qualified_name, language, path, line, column_no, end_line,
    properties, owner_file, external, name_folded, qualified_name_folded
) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
ON CONFLICT(id) DO UPDATE SET
    kind = excluded.kind,
    name = excluded.name,
    qualified_name = excluded.qualified_name,
    language = excluded.language,
    path = excluded.path,
    line = excluded.line,
    column_no = excluded.column_no,
    end_line = excluded.end_line,
    properties = excluded.properties,
    owner_file = excluded.owner_file,
    external = excluded.external,
    name_folded = excluded.name_folded,
    qualified_name_folded = excluded.qualified_name_folded
`

type UpsertNodeParams struct {
	ID                  string `json:"id"`
	Kind                string `json:"kind"`
	Name                string `json:"name"`
	QualifiedName       string `json:"qualified_name"`
	Language            string `json:"language"`
	Path                string `json:"path"`
	Line                int64  `json:"line"`
	ColumnNo            int64  `json:"column_no"`
	EndLine             int64  `json:"end_line"`
	Properties          string `json:"properties"`
	OwnerFile           string `json:"owner_file"`
	External            int64  `json:"external"`
	NameFolded          string `json:"name_folded"`
	QualifiedNameFolded string `json:"qualified_name_folded"`
}

func (q *Queries) UpsertNode(ctx context.Context, arg UpsertNodeParams) error {
	_, err := q.exec(ctx, q.upsertNodeStmt, upsertNode,
		arg.ID,
		arg.Kind,
		arg.Name,
		arg.QualifiedName,
		arg.Language,
		arg.Path,
		arg.Line,
		arg.ColumnNo,
		arg.EndLine,
		arg.Properties,
		arg.OwnerFile,
		arg.External,
		arg.NameFolded,
		arg.QualifiedNameFolded,
	)
	return err
}
