// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: paths.sql

package sqlcgen

import (
	"context"
)

const countPaths = `-- name: CountPaths :one
SELECT COUNT(*) FROM paths
`

func (q *Queries) CountPaths(ctx context.Context) (int64, error) {
	row := q.queryRow(ctx, q.countPathsStmt, countPaths)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const deleteUnreferencedPaths = `-- name: DeleteUnreferencedPaths :exec
DELETE FROM paths
WHERE NOT EXISTS (SELECT 1 FROM facts INDEXED BY facts_path WHERE facts.path_id = paths.id)
  AND NOT EXISTS (SELECT 1 FROM facts INDEXED BY facts_owner WHERE facts.owner_path_id = paths.id)
`

func (q *Queries) DeleteUnreferencedPaths(ctx context.Context) error {
	_, err := q.exec(ctx, q.deleteUnreferencedPathsStmt, deleteUnreferencedPaths)
	return err
}

const internPath = `-- name: InternPath :one
INSERT INTO paths(path) VALUES (?)
ON CONFLICT(path) DO UPDATE SET path = excluded.path
RETURNING id
`

func (q *Queries) InternPath(ctx context.Context, path string) (int64, error) {
	row := q.queryRow(ctx, q.internPathStmt, internPath, path)
	var id int64
	err := row.Scan(&id)
	return id, err
}
