// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlcgen

import (
	"context"
)

type Querier interface {
	ClearDirtyNodes(ctx context.Context) error
	ClearDirtyOwners(ctx context.Context) error
	ClearDirtyTargets(ctx context.Context) error
	ClearReconciliationCleanup(ctx context.Context) error
	CountDirtyFacts(ctx context.Context) (int64, error)
	CountEdges(ctx context.Context) (int64, error)
	CountEdgesByKind(ctx context.Context) ([]CountEdgesByKindRow, error)
	CountExternalNodes(ctx context.Context) (int64, error)
	CountFacts(ctx context.Context) (int64, error)
	CountFiles(ctx context.Context) (int64, error)
	CountNodeMatchesByName(ctx context.Context, arg CountNodeMatchesByNameParams) (CountNodeMatchesByNameRow, error)
	CountNodeMatchesByQualifiedName(ctx context.Context, arg CountNodeMatchesByQualifiedNameParams) (CountNodeMatchesByQualifiedNameRow, error)
	CountNodeMatchesBySubstring(ctx context.Context, arg CountNodeMatchesBySubstringParams) (CountNodeMatchesBySubstringRow, error)
	CountNodes(ctx context.Context) (int64, error)
	CountNodesByKind(ctx context.Context) ([]CountNodesByKindRow, error)
	CountPaths(ctx context.Context) (int64, error)
	// An edge stores only what reconciliation can resolve differently from its
	// originating fact: the resolved endpoints, the relation kind (a structural
	// test edge is derived from a calls or references fact), and the properties
	// (destination evidence and test-coverage evidence are added per edge). Its
	// producer and location are the fact's, so they are joined back instead of
	// stored twice. origin_resolved lets the adapter fail closed on an index whose
	// edge has lost its fact or interned path rather than report an empty location.
	DeleteAllEdges(ctx context.Context) error
	DeleteDirtyFactBatch(ctx context.Context, limit int64) error
	DeleteEdgesByDirtyFactBatch(ctx context.Context, limit int64) error
	DeleteEdgesByOwnerFacts(ctx context.Context, path string) error
	DeleteExternalNodes(ctx context.Context) error
	DeleteFactsByOwner(ctx context.Context, path string) error
	DeleteFile(ctx context.Context, path string) error
	DeleteNodesByOwner(ctx context.Context, ownerFile string) error
	DeleteOrphanExternalNodes(ctx context.Context) error
	DeleteUnreferencedPaths(ctx context.Context) error
	EnqueueDirtyFacts(ctx context.Context) error
	FindNodesExact(ctx context.Context, target string) ([]FindNodesExactRow, error)
	FindNodesExactKind(ctx context.Context, arg FindNodesExactKindParams) ([]FindNodesExactKindRow, error)
	GetMeta(ctx context.Context, key string) (string, error)
	GetNode(ctx context.Context, id string) (Node, error)
	InsertEdge(ctx context.Context, arg InsertEdgeParams) error
	InternPath(ctx context.Context, path string) (int64, error)
	ListCanonicalMessages(ctx context.Context, arg ListCanonicalMessagesParams) ([]Node, error)
	ListDirtyFactBatch(ctx context.Context, limit int64) ([]ListDirtyFactBatchRow, error)
	ListEdgesFrom(ctx context.Context, fromID string) ([]ListEdgesFromRow, error)
	ListEdgesTo(ctx context.Context, toID string) ([]ListEdgesToRow, error)
	ListExternalEdgesMatching(ctx context.Context, arg ListExternalEdgesMatchingParams) ([]ListExternalEdgesMatchingRow, error)
	ListExternalNodesMatching(ctx context.Context, arg ListExternalNodesMatchingParams) ([]Node, error)
	ListExternalRequestEdges(ctx context.Context, arg ListExternalRequestEdgesParams) ([]ListExternalRequestEdgesRow, error)
	ListFiles(ctx context.Context) ([]File, error)
	ListIncomingRelationEdges(ctx context.Context, arg ListIncomingRelationEdgesParams) ([]ListIncomingRelationEdgesRow, error)
	ListNodesByKind(ctx context.Context, arg ListNodesByKindParams) ([]Node, error)
	ListOutgoingRelationEdges(ctx context.Context, arg ListOutgoingRelationEdgesParams) ([]ListOutgoingRelationEdgesRow, error)
	ListSemanticCandidateNodes(ctx context.Context) ([]Node, error)
	MarkDirtyNode(ctx context.Context, nodeID string) error
	MarkDirtyOwner(ctx context.Context, ownerFile string) error
	MarkDirtyTarget(ctx context.Context, arg MarkDirtyTargetParams) error
	MarkOwnedNamesDirty(ctx context.Context, arg MarkOwnedNamesDirtyParams) error
	MarkOwnedNodesDirty(ctx context.Context, ownerFile string) error
	MarkReconciliationCleanup(ctx context.Context) error
	MatchNodesByName(ctx context.Context, arg MatchNodesByNameParams) ([]Node, error)
	// Selector resolution queries. Each level is narrow and index-backed so
	// ambiguity is decided from complete counts instead of a truncated substring
	// window. nodes_qualified and nodes_name are COLLATE NOCASE indexes, so the
	// case-insensitive equality below stays an index seek; the case-sensitive
	// ("strict") form is counted separately because it is stronger evidence.
	// @external selects the scope rather than discarding one: the adapter asks for
	// local declarations first and falls back to external boundary nodes, so exact
	// evidence about an external target is still exact rather than being pushed down
	// into the weaker substring level.
	MatchNodesByQualifiedName(ctx context.Context, arg MatchNodesByQualifiedNameParams) ([]Node, error)
	MatchNodesBySubstring(ctx context.Context, arg MatchNodesBySubstringParams) ([]Node, error)
	PruneDirtyFacts(ctx context.Context) error
	ReconciliationCleanupPending(ctx context.Context) (bool, error)
	ReconciliationPending(ctx context.Context) (bool, error)
	SearchNodes(ctx context.Context, arg SearchNodesParams) ([]Node, error)
	SetMeta(ctx context.Context, arg SetMetaParams) error
	UpsertFact(ctx context.Context, arg UpsertFactParams) error
	UpsertFile(ctx context.Context, arg UpsertFileParams) error
	UpsertNode(ctx context.Context, arg UpsertNodeParams) error
}

var _ Querier = (*Queries)(nil)
